### ISSUE TITLE
Offer library with Java 7 byte code

### ISSUE THREAD

**Issue by akidee** [lessthanoptimal/BoofCV#100]
I cannot use the latest BoofCV version 0.2.9 in an Android project using Android Studio 2.3, retrolambda and Gradle dependencies:

> Information:Gradle` tasks [:app:assembleFullDebug]
> Error:Error converting bytecode to dex:
>Cause: Dex cannot parse version 52 byte code.
>This is caused by library dependencies that have been compiled using Java 8 or above.
>If you are using the 'java' gradle plugin in a library submodule add 
>targetCompatibility = '1.7'
>sourceCompatibility = '1.7'
>to that submodule's build.gradle file.
>Error:1 error; aborting
>Error:java.lang.RuntimeException: com.android.build.api.transform.TransformException: java.lang.RuntimeException: java.lang.RuntimeException: Unable to pre-dex '.../.gradle/caches/modules-2/files-2.1/org.boofcv/boofcv-learning/0.29/ec09e06af64b80b72a9d74e4ace938e393b9dc84/boofcv-learning-0.29.jar' to '.../app/build/intermediates/transforms/dex/full/debug/folders/1000/10/boofcv-learning-0.29_8767152c6ac21ebf49c2a4fcebb1f42b60c7bc18'
Error:com.android.build.api.transform.TransformException: java.lang.RuntimeException: java.lang.RuntimeException: Unable to pre-dex '.../.gradle/caches/modules-2/files-2.1/org.boofcv/boofcv-learning/0.29/ec09e06af64b80b72a9d74e4ace938e393b9dc84/boofcv-learning-0.29.jar' to '.../app/build/intermediates/transforms/dex/full/debug/folders/1000/10/boofcv-learning-0.29_8767152c6ac21ebf49c2a4fcebb1f42b60c7bc18'
Error:java.lang.RuntimeException: java.lang.RuntimeException: Unable to pre-dex '.../.gradle/caches/modules-2/files-2.1/org.boofcv/boofcv-learning/0.29/ec09e06af64b80b72a9d74e4ace938e393b9dc84/boofcv-learning-0.29.jar' to '.../app/build/intermediates/transforms/dex/full/debug/folders/1000/10/boofcv-learning-0.29_8767152c6ac21ebf49c2a4fcebb1f42b60c7bc18'
Error:java.lang.RuntimeException: Unable to pre-dex '.../.gradle/caches/modules-2/files-2.1/org.boofcv/boofcv-learning/0.29/ec09e06af64b80b72a9d74e4ace938e393b9dc84/boofcv-learning-0.29.jar' to '.../app/build/intermediates/transforms/dex/full/debug/folders/1000/10/boofcv-learning-0.29_8767152c6ac21ebf49c2a4fcebb1f42b60c7bc18'

My source/target code compatibility is 1.8, but Java 8 byte code is not acceptable if Java 8 features, Android Studio < 3 (implies retrolambda) are used with minSdkVersion < 26.

Please offer your library with Java 7 byte code class files [if possible](https://stackoverflow.com/a/23757061/6307827).

**Comment by lessthanoptimal** [comment]
Would using a newer version of Android studio fix the issue? A new version of BoofCV is coming out soon and it's 1.8 is the minimum version of Java.

**Comment by lessthanoptimal** [comment]
BoofCV 0.30 is out which does have 1.8 as the minimum requirement. Going to close this issue but feel free if you think there's a strong need for 1.7 jars. Maybe the thing to do is provide instructions on how to build jars like that.
