### ISSUE TITLE
Request to add GrayU16 as a data type to methods in BlurImageOps

### ISSUE THREAD

**Issue by nicost** [lessthanoptimal/BoofCV#111]
Blurring a GrayU16 image currently does not work because the necessary functions are missing from boofcv.alg.filter.blur.BlurImageOps.java.  All images I work with are GrayU16, and converting them to float is a bit sad.  Can the necessary versions of BlurImageOps.gaussian and BlurImageOps.mean be added?  It would then also be nice to have these accessible through GBlurImageOps. 

I'd be happy to do this myself, but I can not figure out how to run the code generating code (./gradlew assemble does something, but not what I hoped for).

**Comment by lessthanoptimal** [comment]
In your IDE you can just right click and run the class. it will output the results to the working directory.

**Comment by lessthanoptimal** [comment]
just double checked to make sure I wasn't sending you down the wrong path. This code is auto generated, but after tracking through it there are a few different auto code generators involved, e.g. image border, inner image, convolution, ...etc. I'll just do this one

**Comment by lessthanoptimal** [comment]
done. check latest SNAPSHOT  code. Re-open if you find an issue
