### ISSUE TITLE
Thresholding of Unsigned 16-bit Images

### ISSUE THREAD

**Issue by lessthanoptimal** [lessthanoptimal/BoofCV#113]
- Update DemoImageThresholdingApp so that it automatically selects the best image type from input
  * Rescale to 8-bit then thresholding in 16 bits?

@nicost Let's use this to talk about missing features

**Comment by nicost** [comment]
I don't know what the display capabilities are , but it would be nicest to keep the image 16 bits while calculating the threshold.  For most methods speed will be a non-issue (except for the Huang method), and results should be more precise.  It would also be nice if the app would display the threshold numerically.

**Comment by lessthanoptimal** [comment]
Feature has been added. Closing ticket.
