### ISSUE TITLE
Finish ImageBandMath

### ISSUE THREAD

**Issue by lessthanoptimal** [lessthanoptimal/BoofCV#118]
- Function parameters are (almost) always input first then output, e.g. input, start, last, output ... etc
  * ~~Update all function in ImageBandMath, GImageBandMath, ImplImageBandMath~~
  * ~~Don't forget to update GenerateImplImageBandMath !~~
  * Revert my change to order in stdDev (see next comment)
- In ImageBandMath reshape output so that it matches the input, i.e. output.reshape(input.width,input,height)
- Add @Nullable to ave in stdev
- Create a GenerateImageBandMath
- Add parallelization comments to ImplImageBandMath then generate a concurrent version
- Update ImageBandMath to toggle the serial or parallel code
- Create a unit test for ImplImageBandMath_MT that compares the output from parallel code to serial

**Comment by lessthanoptimal** [comment]
The function arguments are more like: (inputs ... , outputs ... , optional parameters) with convolution its ( kernel, input, output, border) border is considered optional because it can have a default value.

When I first looked at your  code I only saw ImageBandMath. In GImageBandMath you have start + last band as optional arguments. In that case you should have them at the end. However, for stdDev avg you could argue that it is required or not (since null is allowed).

**Comment by nicost** [comment]
- firstband and lastBand are (or should be) optional parameters.  My sense was that handling that in GImageBandMath was enough, but I can add versions for these in ImageBandMath if you think that is helpful. I can change the types to Integer and indicate that they are nullable (but I prefer primitives whenever possible)

- I am confused about the order of parameters that you would like.  If it is input, output, optional, then in all cases it should be: input, output, firstBand, lastBand.  For StdDev, avg should be an optional parameter as well.  As a user, I would be confused if the argument order differs between GImageBandMath and ImageBandMath (which currently is the case).  It may be best to add overloaded versions that lack all optional parameters to ImageBandMath to make clear that firstBand, lastBand, and avg (in the std. Dev. functions) are in fact optional.

- Does it make sense to make output nullable? It would be easy enough to create and doing so will save a line in the calling code. However, this does not seem the be the convention in other parts of boofCV.

**Comment by nicost** [comment]
Just pushed a commit that addresses all but the last two of the points you raised to https://github.com/nicost/BoofCV/tree/imageBandMath.  I figured out how to generate the MT code, but that generates a lot of errors elsewhere in the project (due to a missing import, I guess something changed place recently), let me know when I can continue with the multi-threading code.
- I noticed that you forced a medianBand projection of a single plane to result in 0 values.  That does not seem right to me (the median of a single number is that number, moreover, forcing this to 0 will lead to difficult to interpret results for the end user).  I reverted to simply copying the values of the given plane.
- Let me know if the argument order makes sense now.  It should be easy to move them around now.

**Comment by lessthanoptimal** [comment]
* I didn't touch GImageBandMath much. Figured we could synchronize it with the others later
* I'll look at what you did for argument order when I get back. 
* The median being set to 1 was a mistake! I remember putting the code in but was thinking of standard deviation. Fixing that now. as for stdev... I guess just leave it the way it is, which will result in NaN.
* I checked and your ImplImageBandMath code has
    //CONCURRENT_INLINE import boofcv.concurrency.BoofConcurrency;
   but it's missing in the final output. Can you run AutocodeConcurrentApp again?
* There were some other auto generated classes which were missing the //CONCURRENT import statement. That has been fixed and if you run AutocodeConcurrentApp everything should still build.

**Comment by nicost** [comment]
Now also finished the last two points (ImageBandMath calling MT code when appropriate, and testing of MT versus ST code).  However, since you also made changes to these files, they do not merge cleanly.  Let me know how you want to proceed.  My latest code is in https://github.com/nicost/BoofCV/tree/imageBandMath

**Comment by lessthanoptimal** [comment]
Could you try the merge yourself? In this case I would glance at my code, ensure that there are no differences which are significant and not already addressed by our discussion. If that's the case the merge might be really simple. basically tell it to use your version and ignore mine.

**Comment by lessthanoptimal** [comment]
quick note. Make sure you pull the latest code before you start this merge. Also what tools do you use for merging code? I've been surprised how many people do it the painful way. I typically use a visual tool, like what's built into IntelliJ firs. If it's a really complex merge then I jump into the actual file with all raw diff markers.

**Comment by lessthanoptimal** [comment]
Benchmark Results

`Benchmark                       (concurrent)  (numBands)  (size)  Mode  Cnt     Score     Error  Units
BenchmarkImageBandMath.average          true          10    5000  avgt   10    88.931 ±   1.322  ms/op
BenchmarkImageBandMath.average          true          11    5000  avgt   10    88.812 ±   0.924  ms/op
BenchmarkImageBandMath.average         false          10    5000  avgt   10   329.856 ±   3.633  ms/op
BenchmarkImageBandMath.average         false          11    5000  avgt   10   325.537 ±   1.065  ms/op
BenchmarkImageBandMath.maximum          true          10    5000  avgt   10    96.932 ±   3.789  ms/op
BenchmarkImageBandMath.maximum          true          11    5000  avgt   10   101.174 ±   7.786  ms/op
BenchmarkImageBandMath.maximum         false          10    5000  avgt   10   345.449 ±  10.918  ms/op
BenchmarkImageBandMath.maximum         false          11    5000  avgt   10   323.344 ±   1.743  ms/op
BenchmarkImageBandMath.median           true          10    5000  avgt   10   688.470 ±  18.442  ms/op
BenchmarkImageBandMath.median           true          11    5000  avgt   10   686.964 ±  21.145  ms/op
BenchmarkImageBandMath.median          false          10    5000  avgt   10  3890.114 ± 339.288  ms/op
BenchmarkImageBandMath.median          false          11    5000  avgt   10  3835.045 ±  92.919  ms/op
BenchmarkImageBandMath.minimum          true          10    5000  avgt   10    97.839 ±   4.970  ms/op
BenchmarkImageBandMath.minimum          true          11    5000  avgt   10    94.038 ±   1.470  ms/op
BenchmarkImageBandMath.minimum         false          10    5000  avgt   10   345.421 ±  41.904  ms/op
BenchmarkImageBandMath.minimum         false          11    5000  avgt   10   347.157 ±  21.924  ms/op
BenchmarkImageBandMath.stdDev           true          10    5000  avgt   10   139.564 ±  16.995  ms/op
BenchmarkImageBandMath.stdDev           true          11    5000  avgt   10   139.888 ±  13.145  ms/op
BenchmarkImageBandMath.stdDev          false          10    5000  avgt   10   522.809 ±   8.326  ms/op
BenchmarkImageBandMath.stdDev          false          11    5000  avgt   10   519.474 ±   3.108  ms/op`

**Comment by lessthanoptimal** [comment]
I'm going to start preparing for a new stable release. Is there anything else you would like to see added? @nicost 

Also considering changing BoofConcurrency.range into BoofConcurrency.loopFor. Then BoofConcurrency.blocks into BoofConcurrency.loopBlocks for readability. Any thoughts on that?

**Comment by nicost** [comment]
Nothing I can think of right now.  In the long term I may want to look into 3D filters, segmentation, and binary operations (i.e. procedures that act on Planar<T> and considers them to be 2D planes in a 3D space, but I have no immediate need yet.

I like the name change you propose.  It better explains what is happening. 

The Benchmarks look great!  Elegant solution for handling the "even" case in the median code, there now does not seem to be any speed penalty for being even!
