### ISSUE TITLE
Boofcv android sample 

### ISSUE THREAD

**Issue by Revathy14** [lessthanoptimal/BoofCV#126]
The sample which runs on 0.31 hangs upon scanning the square fiducial on Android 8.1 device. To be specific Samsung J5. Tried to modify Gradle to use 33.1 but there are lots of errors as the classes have been removed/renamed. Pleas do help provide some help in this regard. Thanks in advance

**Comment by lessthanoptimal** [comment]
I've covered this in the discussion. It's an issue related to the use of Java 1.8 features to add threading to boofcv. The fix is to turn off concurrency with BoofConcurrency.USE_CONCURRENT = false. If you are using API 24 and above then you should not need to turn off concurrency.
