### ISSUE TITLE
ImplBilinearPixel and GenerateImplBilinearPixel out of sync?

### ISSUE THREAD

**Issue by nicost** [lessthanoptimal/BoofCV#128]
Started to use the "FDistort" class and run into the issue that some of the interpolation methods for GrayU16 images are missing.  Started to add those, but discovered that the generated code does not compile.  It looks like the code in /boofcv-ip/src/main/java/boofcv/alg/interpolate/impl/ImplBiLinearPixel* was not generates by the code currently in /boofcv-ip/src/generate/java/boofcv/alg/interpolate/impl/GenerateImplBilinearPixel.  Specifically, the first has a "copy" function that is not generated by the generator code.  This is all in the SNAPSHOT branch.  Am I missing something?

**Comment by lessthanoptimal** [comment]
Looks like it got refactored but the generator didn't get updated. newInstance() is now copy()

**Comment by nicost** [comment]
Perfect.  Added that change to PR #129.
