### ISSUE TITLE
Template matching with mask

### ISSUE THREAD

**Issue by talarari** [lessthanoptimal/BoofCV#130]
Hey, Im trying to use boofcv on android to do some template matching.
im trying to match an icon on a screenshot, without a mask different backgrounds make it give bad matchs.
the template is the icon with a transparent background, i want to create a mask to make this work better as shown here:
https://boofcv.org/index.php?title=Example_Template_Matching

im a little confused about how the mask should look and how to create it.
for the cursor example this is the template and mask provided:
![cursor](https://raw.githubusercontent.com/lessthanoptimal/BoofCV-Data/58005f9bbb57c39414a575bfbe7a79f1a30fb5c0/example/template/cursor.png
 "Cursor")

![cursor mask](https://raw.githubusercontent.com/lessthanoptimal/BoofCV-Data/58005f9bbb57c39414a575bfbe7a79f1a30fb5c0/example/template/cursor_mask.png "Cursor mask")

the docs here: 
http://boofcv.org/javadoc/boofcv/alg/feature/detect/template/TemplateMatching.html
Say this:
mask - Optional mask. Same size as template. 0 = pixel is transparent, values larger than zero determine how influential the pixel is. Can be null.

so the black parts should be over the what you want to match no? so i would expect the black parts in the mask to be on the background.
what should the mask look like?

also how can i create the mask from the alpha channel on the bitmap (transparent background) programmatically? 

BTW im getting bad results mainly with light backgrounds (if the icon is on a white wallpaper instead of a black wallpaper for instance)

This library is awesome, started with opencv on android and that was pretty difficult to even get started with.

**Comment by talarari** [comment]
Also if im going about this the wrong way i'd love some guidance, i want to match an element in a screenshot basically.

**Comment by talarari** [comment]
Small update, got the template to match pretty well, but if i i take a screenshot with larger icons i doesn't match anymore.
any suggestion on how to make this work on different scales?

I'm also considering using feature association between the template and the input image and then average out a point where most matches are or something of that sort, but im getting matches all over the place, is that a good approach?

aiming at something like this:
http://robocv.blogspot.com/2012/02/real-time-object-detection-in-opencv.html?m=1
should be even easier if the images are screenshots and icons and there's no lighting changes and input quality is very good.

**Comment by lessthanoptimal** [comment]
Templates don't work at different scales. Well you could create an image pyramid and run the same place at each level. Perhaps a better way to handle it is to get the images DPI and scale it to some standard resolution? That information I believe is accessible.

The "feature homography" example you posted can be done in BoofCV. it tends to work on larger complex flat objects, say a painting, and might not work so well on a simplistic logo. Just need to experiment and see if it works.

Do you have any suggestions on how to improve the documentation to make things clearer?

**Comment by talarari** [comment]
Will be trying matching at different scales with an image pyramid (that's just a fancy name for matching target image at different scales and using the best match right?) 

I tried feature homography with another sample app that uses opencv, as you said it worked very well for a dollar bill but terribly for an icon.

I've also experimented with the different types of template matching algorithms provided in boofcv. 
mostly SUM_DIFF_SQ and NCC

i'm having trouble setting a good threshold for matching, i will be matching lots of different templates and want a dynamic way of setting the threshold.
i though normalized cross correlation would be good since from what i've read its supposed to return 1 for a perfect match and 0 for the worst match, that way i could just set 0.7 or something and be done.
but in reality i see it returning different unbounded scores, 600, 800, 1300 etc  

is this by design? how would you approach setting the threshold?

regarding the documentation about the mask, i was uncertain about whether the black part of the mask should be on the object or on the background. some clarification about that would be great

**Comment by talarari** [comment]
Also in the meantime i tried matching the template against itself for getting the best match score and normalizing the score myself but when i do that i get no matches, that seems very weird 
any idea why this happens?

**Comment by shortpasta** [comment]
Same question here - if I match with SUM_DIFF_SQ, what is the score scale/range/matrix?
I tried different image/template combinations, and I get values from -9,961,941.0 to -9.1.
What about NCC and CORRELATION?

**Comment by sschava1** [comment]
@talarari, @shortpasta were you able to find the range or bounds on SUM_DIFF_SQ, NCC and CORRELATION?

**Comment by shortpasta** [comment]
Negative.This was taking too much time so I had to pause it.I am not sure when I will be able to get back to it.
    On Tuesday, September 3, 2019, 01:57:16 PM PDT, Shirish Chavan <notifications@github.com> wrote:  
 
 
@talarari, @shortpasta were you able to find the range or bounds on SUM_DIFF_SQ, NCC and CORRELATION?

**Comment by waicool20** [comment]
You can get a normalized output (values 0 to 1) if you divide the score by the squared sum product of the template and image. But for that you will need a custom EvaluatorMethod class which you can then use with your matcher. Since template and image were package protected I had to get a bit hacky: 

https://github.com/waicool20/CVAuto/blob/master/modules/core/src/main/kotlin/com/waicool20/cvauto/util/matching/TemplateDiffSquaredNorm.kt

OpenCV has some handy equations written if you need some reference: 
https://docs.opencv.org/2.4/doc/tutorials/imgproc/histograms/template_matching/template_matching.html

**Comment by lessthanoptimal** [comment]
* How do other libraries handle this problem? Do any enforce a value between 0 and 1?
* Any other error functions that you would like which are currently missing?
* Any other improvements?

I don't personally use template matching much so this part of the code hasn't gotten as much love as others.

**Comment by waicool20** [comment]
As far as I know, only the normalized methods in opencv have bounded outputs from 0 to 1, others are unbounded like boofcv has it. This is useful for having consistent thresholding if you say wanted to switch different matching methods for different operations which may or may not need the accuracy but need the speed. And as an end user of an app that uses template matching, 0.9 corresponding to 90% similarity is more intuitive to understand than some arbitrary number.

**Comment by lessthanoptimal** [comment]
I'm going to close this ticket. Don't see a huge benefit to ensuring output from 0 to 1 for some functions. Did tweak NCC a bit to make it more similar to OpenCV and it slightly reduced the number of flops.
