### ISSUE TITLE
Polygon2D_F64 isCCW() method showing inconsistency with the order of points.

### ISSUE THREAD

**Issue by ivanquirino** [lessthanoptimal/BoofCV#132]
Consider the following code:
```
var bounds = qrCode.bounds;

    var p1 = bounds.get(0);
    var p2 = bounds.get(1);
    var p3 = bounds.get(2);
    var p4 = bounds.get(3);

    System.out.println(bounds.isCCW());
    System.out.println(p1);
    System.out.println(p2);
    System.out.println(p3);
    System.out.println(p4);
```
Which produced this output:
```
true
P(  1220,7  130,88 )
P(  1404,14337  130,880887 )
P(  1404,14893  314,281198 )
P(  1220,70021  314,279769 )
```

This shows a clockwise order, even if `isCCW()` is `true`. Is this specific to QRCodes? I'm using version 0.33.1.

**Comment by lessthanoptimal** [comment]
That is correctly identified as counter clockwise order. What I think is causing confusion is that in image processing the +y axis points down, while in every other field the standard points up. To verify this, sketch those coordinates with +y up and +x right and you will see it's counter clockwise. The Polygon2D data type is part of a generic geometry library so it uses +y up and right handed coordinate system.

**Comment by ivanquirino** [comment]
@lessthanoptimal of course, I forgot that, sorry. Thanks again. 

There would be any problem in licensing if I would port Boof's QrCode detector to OpenCV? They use a 3 clause BSD licence while Boof uses Apache 2.0. While Boof's is so great and OpenCV' sucks so much, we may lend them a hand...

**Comment by lessthanoptimal** [comment]
I think I would have allow the code to have a dual license BSD and Apache 2.0. The biggest issue is that the code would be difficult port. While a lot of the operations in OpenCV and BoofCV should be "equivalent" based on their description they aren't. Hard to say how significant those differences are until you try. I did start a C++ of BoofCV called BoofCPP, but it's far from complete. Stopped it because it didn't have large enough performance gains to justify the effort.

**Comment by ivanquirino** [comment]
What if I ported the algorithm? Writing Boof's algorithm using OpenCV API instead of a direct port? Would this break the license? Another question is about creating a library for React Native using BoofCV Android, I would have as dependencies boofcv-core and boofcv-android, would the size be too big or I would have to make a fork and remove unused packages?

**Comment by lessthanoptimal** [comment]
I don't think licensing will be an issue. We can double check by asking them if a dual license is acceptable.

I do think that using OpenCV functions, when applicable, is the way to go, but I suspect that in some cases there won't be direct analogs. For example, look at the SURF comparison on the website. In other situations the tuning parameters are completely different.  At the same time I think you would end up with something vastly superior to their current QR Code algorithm, just not as good as what's in BoofCV right now.

Never messed with React Native so can't help you there.

**Comment by ivanquirino** [comment]
I think I'll let that for someone with more C++ knowledge than me. Thanks
for everything! Is there any library or toolkit for converting images
between BoofCV to OpenCV and the way back besides saving the image and
opening again?

Ivan Quirino
Desenvolvedor Líder - Yupi Studios
Desenvolvimento Web
Analista de Redes de Computadores

**Comment by lessthanoptimal** [comment]
There's already a wrapper for [JavaCV](https://github.com/lessthanoptimal/BoofCV/blob/3898140b1ab435f766a176688aadb226e275a9e0/integration/boofcv-javacv/src/main/java/boofcv/javacv/ConvertIplImage.java)

**Comment by ivanquirino** [comment]
I'm using the official opencv java wrappers and I tried JavaCV and
discovered that JavaCV is missing some basic Mat methods like submat(). I
may be missing something, but I couldn't make JavaCV work with my existing
code, so I kept going with the opencv package.

Ivan Quirino
Desenvolvedor Líder - Yupi Studios
Desenvolvimento Web
Analista de Redes de Computadores

**Comment by lessthanoptimal** [comment]
I'll look into providing integration code for the official java wrapper. Creating a new issue for it

**Comment by ivanquirino** [comment]
@lessthanoptimal many thanks! please mention me when you have something, I'll be the first to test it.
