### ISSUE TITLE
ColorLab labToRgb?

### ISSUE THREAD

**Issue by zhuker** [lessthanoptimal/BoofCV#137]
`ColorLab` has rgbToLab but I can't find the inverse `labToRgb`, is not the right place to be looking for it?

**Comment by lessthanoptimal** [comment]
You're looking in the right place but it isn't in the code. Probably because the inverse formulation wasn't readily available. I'll treat this as a feature request.

**Comment by lessthanoptimal** [comment]
Looks like was added last year! Closing issue.
