### ISSUE TITLE
Better QR Code documentation.

### ISSUE THREAD

**Issue by cosimo17** [lessthanoptimal/BoofCV#139]
I want to know if boofcv can decode qrcode? 
I have another good detector, I want a good decoder.

**Comment by cosimo17** [comment]
> it can. Were you able to get the example code to work? There's also a pre-built application you can use.

yes.I can run the example application refered in quick start guide,but I didn't find decoder example in the application. Could you tell me more details about how to run decoder in boofcv?Thanks.

**Comment by lessthanoptimal** [comment]
Would a video on youtube help?

**Comment by lessthanoptimal** [comment]
Hey! I just updated the QR code documentation and might have accidentally fulfilled this ticket. I know it's been about 1.5 years, but could you take a look and tell me if this helps?

https://boofcv.org/index.php?title=Tutorial_QRCodes

**Comment by lessthanoptimal** [comment]
closing issue since I think it has been resolved.
