### ISSUE TITLE
Latest Stable Release missing GEORegression

### ISSUE THREAD

**Issue by changbaishan** [lessthanoptimal/BoofCV#143]
Hi Peter,

I downloaded from the Latest Stable Release from https://sourceforge.net/projects/boofcv/files/v0.34/

The boofcv-v0.34-libs does not contain GEORegression.

Please correct after verification.

Thank you again for your good work!

**Comment by lessthanoptimal** [comment]
You're right. I just fixed the problem in the latest snapshot. It's probably been broken for a bit because it was due to a change in Gradle 4.  I've uploaded the corrected jar. It's considerably larger.
