### ISSUE TITLE
TemplateMatcher does not work when template and image are equal size

### ISSUE THREAD

**Issue by waicool20** [lessthanoptimal/BoofCV#144]
Template matcher does not work properly when I tried to use the same image as template and match image. 

Looking at the source it doesn't even process the images at all in this case:
```kotlin
// TemplateIntensityImage.java
	@Override
	public void process(T template) {
		this.template = template;
		this.mask = null;
		intensity.reshape(image.width, image.height);

		int w = image.width - template.width;                 //<<<<< ------ 0!
		int h = image.height - template.height;               //<<<<< ------ 0!

		borderX0 = template.width / 2;
		borderY0 = template.height / 2;
		borderX1 = template.width-borderX0;
		borderY1 = template.height-borderY0;

		method.initialize(this);

		processInner(w, h);

		// deference to avoid causing a memory leak
		this.template = null;
		this.mask = null;
	}

	protected void processInner(int w, int h) {
                //>>>>>>> Does not run at all! Because w and h are 0 <<<<<<<
		for (int y = 0; y < h; y++) {
			int index = intensity.startIndex + (y + borderY0) * intensity.stride + borderX0;
			for (int x = 0; x < w; x++) {
				intensity.data[index++] = method.evaluate(x, y);
			}
		}
	}
```
Simply padding the match image by one pixel is enough to make this work properly. Other classes that implement `TemplateMatchingIntensity` seem to have the same problem.

**Comment by waicool20** [comment]
I've rolled out my own solution for now, considering I don't want to mess with pulling the repo as a submodule and using it as a dependency directly.

https://github.com/waicool20/CVAuto/blob/master/modules/core/src/main/kotlin/com/waicool20/cvauto/util/matching/DefaultTemplateIntensityImage.kt

**Comment by lessthanoptimal** [comment]
There's a fix in the latested SNAPSHOT. Could you check that out and double check?

**Comment by waicool20** [comment]
I havn't tested it yet but the changes seem promising, though is it possible to push snapshot builds to maven automatically using your travis builds? I guess I'll just have to pull the repo for now. Also I think it'd be nice if you reference the issue number in your commits so they get linked here, mainly just for convenience and reference.

Also I noticed a typo heh
![image](https://user-images.githubusercontent.com/5538666/69125214-47191680-0ae0-11ea-90ec-26af6a30d350.png)

**Comment by waicool20** [comment]
georegression version 0.21-SNAPSHOT no longer exists on maven central please update `build.gradle`

```groovy        
api (group: 'org.georegression', name: 'georegression', version: '0.21-SNAPSHOT')
```

**Comment by waicool20** [comment]
First thing I notice is that it works, but also not what I expected. Matching an image with itself results with the `x = 1, y = 1` when it should be `x = 0, y = 0`

**Comment by lessthanoptimal** [comment]
Can you create a unit test that replicates that or maybe provide the image and/or post the code + example image? Just checked the unit tests and they make sure it's at (0,0)

**Comment by lessthanoptimal** [comment]
Also fixed the type-o you pointed out earlier!

**Comment by waicool20** [comment]
I've rechecked my test code and it seems like I was padding the image by one pixel beforehand which i forgot to remove. It was the work around i was using before these fixes, seems all good now.

**Comment by lessthanoptimal** [comment]
I updated the .gitignore. Also updated the SNAPSHOT of GeoRegression. However, Travis CI doesn't seem to be having problems right now. Travis does sometimes fail because it can't download jars. Not sure if that's something I can fix.
