### ISSUE TITLE
QrCodeEncoder 6 Bytes under max Bytes for Version

### ISSUE THREAD

**Issue by phillip-fry** [lessthanoptimal/BoofCV#146]
Hello,

This is one of the best QR libraries I've found for working with Android devices, but I found something strange with the QrCodeEncoder.addBytes() function throwing the following error

`java.lang.IllegalArgumentException: Version and error level can't encode all the data
at boofcv.alg.fiducial.qrcode.QrCodeEncoder.autoSelectVersionAndError(QrCodeEncoder.java:681)
at boofcv.alg.fiducial.qrcode.QrCodeEncoder.fixate(QrCodeEncoder.java:482)`

So I understand that it is saying I'm trying to add too many bytes for the QrVersion specified, but it doesn't make sense because I've referred to values provided by `QrCode.VERSION_INFO`. I found that for almost every QR Version I've tried to set, if I want to call `addBytes()` I have to be 6 bytes under the max specified for the version.

Pseudo Code Example (Kotlin):
`
// This should is 1455 Bytes for Error Correction level Medium for Version 31
val bytesForFrame : Int = QrCode.VERSION_INFO[31].totoalDataBytes(QRCode.ErrorLevel.M)

// Now I specify the encoder I want Version 31 with ErrorLevel Medium
val encoder = QrCodeEncoder()
encoder.setError(QrCode.ErrorlLevel.M)
encoder.setVersion(31)
encoder.addBytes(__packet__) // packet is a ByteArray of size 1455
`

Now I kept dropping byte by byte off the __packet__ size and when I reduced it to 6 under (1,449) then it would allow me to add the bytes.

I'm just wondering if this is expected behavior because if is a ByteArray. Any information regarding this behavior would be greatly appreciated, and thank you for the cool library.

I am also using version 0.33 and running only on Android devices at the moment.

**Comment by lessthanoptimal** [comment]
I'm going to look into this but got a tangential question for you. Do you think there would be a significant bonus for Kotlin users if there was a Kotlin wrapper for some functions in BoofCV? I'm a Kotlin novice and have been using it for writing quick one-offs with BoofCV and right now I don't think there would be a big benefit.

**Comment by lessthanoptimal** [comment]
Good news, good news, bad news.

1. I made that error message much more informative
2. There was a bug in the conversion from bits to bytes where it incorrectly handled the remainder. Effectively you can add 0 to 7 more bytes depending on the message
3. Your packet is still too big

Here's the new error message:

`Version and error level can't encode all the data. Version = 31 , Error = M , Encoded Bits = 11644 , Overhead Bits = 16 , Data Bytes = 1458 , Limit Bytes = 1455`

**Comment by phillip-fry** [comment]
Hello,

I apologize for the delay in response. Thank you for looking into this and adding more detail to the error messages.

Regarding writing a Kotlin wrapper for BoofCV, I would put it as a low priority, but I am not sure how beneficial it would be as I am fairly new to Kotlin as well. This is my first application using the language and I have found Kotlin and Java libraries work very well together. I haven't had any troubles using BoofCV with Kotlin so far.

Thanks again.

**Comment by lessthanoptimal** [comment]
Work has started on Kotlin integration checkout the issue below for a discussion

https://github.com/lessthanoptimal/BoofCV/issues/148

I'm going to close this issue, but feel free to open it again if there's still a problem.
