### ISSUE TITLE
Avermedia cannot opened as WebCam

### ISSUE THREAD

**Issue by okandonmez** [lessthanoptimal/BoofCV#147]
Hi,

I am trying to calibrate my camera which is FishEye and connected with AverMedia. In the GUI when i try to calibrate with webcam, in the list i can see the my camera name but when i choose it on calibration page the GUI shows me the Integrated Camera frames. Has any idea about the solution ?

**Comment by lessthanoptimal** [comment]
1. Could you explain what you mean by "integrated camera frames"?
2. This also might be an issue with http://webcam-capture.sarxos.pl/ which is the webcam library that BoofCV uses.
3. Do you plan on using assisted calibration?

**Comment by okandonmez** [comment]
Firstly, i want to use your app for assisted camera calibration. I am trying your app on my laptop and laptop has integrated camera on the screen. Integrated camera frames means the just camera footage :) So i check on the link which you suggest me for maybe source of the problem but I solved the problem with a desktop computer without another integrated camera. Thanks for an amazing app and your interest for my issue.
