### ISSUE TITLE
i had a issues by running the class file of  ExampleDetectQrCode  in intellij IDE.

### ISSUE THREAD

**Issue by vijay180396** [lessthanoptimal/BoofCV#149]
> Task :main:boofcv-types:compileJava FAILED
14 actionable tasks: 13 executed, 1 up-to-date

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':main:boofcv-types:compileJava'.
> java.lang.ExceptionInInitializerError (no error message)

**Comment by lessthanoptimal** [comment]
that's weird. Have you tried building it again? Somethings CI fails randomly due to network issues, i.e. it can't download a jar it needs. That error message doesn't say much.

 What version of Java and BoofCV are you using?

**Comment by vijay180396** [comment]
java version:11
boofcv version:0.36

**Comment by lessthanoptimal** [comment]
0.36? So the latest SNAPSHOT code. You might have gotten unlucky and grab a bad SNAPSHOT. Try this.

```
git fetch --all
git checkout SNAPSHOT
git reset --hard origin/SNAPSHOT
```

**Comment by vijay180396** [comment]
thank you it,s worked

**Comment by vijay180396** [comment]
And more think it's about stitching.In boofcv there only possibility of stitching an images by two

**Comment by JairoRotava** [comment]
I have same issue trying to build any file on Intellij IDE. I always get this error: 
Execution failed for task ':main:boofcv-types:compileJava'. 

The last line on the stack exception is: 	
at jdk.attach/sun.tools.attach.AttachProviderImpl.attachVirtualMachine(AttachProviderImpl.java:58)
	at jdk.attach/com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:207)

But I can build  using the gradlew on terminal without problem. BoofCV version is SANPSHOT, OpenJDK is 11 (tried 13 too). Already tried to clone again, and the suggestions above. 

I'm new to Java, so I'm not sure what could be wrong.

**Comment by vijay180396** [comment]
thanks for your, information
