### ISSUE TITLE
Minimal Android Samples

### ISSUE THREAD

**Issue by eschoenawa** [lessthanoptimal/BoofCV#155]
It took me quite some time to understand how to use the library on Android. The demo app, while showing off many features, has a challenging codebase when you are just interested in one feature as you run across multiple places that are not relevant for what you want to achieve. What doesn't help is that both activities provided by the library and the single one provided in the demo all contain quite a lot of the logic and violate separation of concerns on multiple places, making them massive.

What would help here would be minimal sample apps each showing off single features. This would also excuse rougher architecture as there wouldn't be as much code to get lost in. Alternatively a more polished big demo app, implementing modern Android best practices and maybe separating features into gradle modules, would go a long way.

**Comment by lessthanoptimal** [comment]
You're right about the issues with learning from the demo application. There are two minimalist examples in the BoofCV code base now, but they aren't advertised very well.

https://github.com/lessthanoptimal/BoofCV/tree/SNAPSHOT/integration/boofcv-android/examples/video

Is that what you hope to see? I can make it easier to find.

**Comment by eschoenawa** [comment]
Hell yeah, that's exactly what I was looking for! I'd really recommended making them easier to find and possibly expanding the offer (yourself or by others). The package name 'video' could make these challenging to find, maybe it should be changed.

**Comment by lessthanoptimal** [comment]
Android Demo readme now references these examples
https://github.com/lessthanoptimal/BoofAndroidDemo/

Might have time this weekend to improve update the website too

**Comment by lessthanoptimal** [comment]
done, it's in the integration examples and the demo code references it correctly.
