### ISSUE TITLE
Artifacts when switching between Swing Look and Feel

### ISSUE THREAD

**Issue by weisJ** [lessthanoptimal/BoofCV#157]
https://github.com/lessthanoptimal/BoofCV/blob/cd9f242e700579ced6b1df430d9e0f31448b5ba5/integration/boofcv-swing/src/main/java/boofcv/gui/settings/GlobalSettingsControls.java#L120

Is it necessary to restart when the LaF is changed?

**Comment by lessthanoptimal** [comment]
The window which is currently open doesn't update. I tried a few things like invalidating and didn't work. A solution would be very much welcome.

**Comment by weisJ** [comment]
You can use ` SwingUtilities#updateComponentTreeUI` for each open window. Alternatively there is `LafManager#updateLaf` which handles that automatically.

**Comment by lessthanoptimal** [comment]
`SwingUtilities#updateComponentTreeUI` mostly works. Going to remove the warning dialog but there is a little bit of residue from previous themes. Like a tab gets stuck with the color green.

**Comment by lessthanoptimal** [comment]
Did a bit more testing. If I stay within your LAFs the transition isn't bad. if I switch to LAF from different authors things get messed up.  I used your `updateLaf` function in the end.

**Comment by weisJ** [comment]
The residues from different lafs might be due to some thing not being updated. Do you query colours etc. from The UIManager inside the constructor of components or cellrenderers? If yes you should move those into `JComponent#updateUI` and reinitialise  the renderers in `updateUI` (or instead query the colours each time the renderer component gets requested).

**Comment by lessthanoptimal** [comment]
Most of the components are standard without any significant modifications. Looks more like some LAF modify some settings and others don't. So when you switch you end up in a weird hybrid state.

**Comment by lessthanoptimal** [comment]
Closing this issue since its just a minor nuance and there is no plan to fix it.
