### ISSUE TITLE
support 1d Barcode

### ISSUE THREAD

**Issue by moradi-morteza** [lessthanoptimal/BoofCV#166]
hello
i use boofcv
does it support 1d Barcode?
if true where is the documentation and sample for android?
i test it and work for qrcode but not work for 1d barcode.
thanks

**Comment by lessthanoptimal** [comment]
No support currently. There's already a feature request for it (Issue https://github.com/lessthanoptimal/BoofCV/issues/102) and it could be added in the future, but not in the "schedule" at the moment.
