### ISSUE TITLE
v0.36.1 not load from Maven in IntellijIDEA

### ISSUE THREAD

**Issue by olegvakulenko** [lessthanoptimal/BoofCV#169]
I change pom.xml.

Before:

```
<dependency>
	<groupId>org.boofcv</groupId>
	<artifactId>boofcv-core</artifactId>
	<version>0.36</version>
</dependency>
```

After:

```
<dependency>
	<groupId>org.boofcv</groupId>
	<artifactId>boofcv-core</artifactId>
	<version>0.36.1</version>
</dependency>
```

And got error:
`Could not find artifact org.boofcv:boofcv-core:pom:0.36.1 in central (https://repo.maven.apache.org/maven2)`

**Comment by lessthanoptimal** [comment]
haha yeah I was hoping to sneak that one past people since doing a formal release is a bit of a pain. It just contains fixes related to running inside of a jar. I'll upload it to maven central to avoid confusion.

**Comment by lessthanoptimal** [comment]
It's on Sonatype. Try it now. if that doesn't work wait an hour or two for their servers to refresh.

**Comment by olegvakulenko** [comment]
Cannot resolve org.boofcv:boofcv-core:0.36.1

**Comment by lessthanoptimal** [comment]
https://search.maven.org/artifact/org.boofcv/boofcv-core/0.36.1/jar

you should be good now

**Comment by olegvakulenko** [comment]
Now works.
Thanks!
