### ISSUE TITLE
An illegal reflective access operation has occurred

### ISSUE THREAD

**Issue by GenieTim** [lessthanoptimal/BoofCV#175]
Thank you for this awesome library. 
When using it, I get the following warnings:

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by boofcv.io.image.ConvertRaster (file:/<redacted>/.m2/repository/org/boofcv/boofcv-io/0.36.1/boofcv-io-0.36.1.jar) to method sun.awt.image.ByteInterleavedRaster.getDataOffset(int)
WARNING: Please consider reporting this to the maintainers of boofcv.io.image.ConvertRaster
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

As these are only warnings, I am not sure if you want to take a closer look at all; I herewith just comply with "Please consider reporting this to the maintainers of boofcv.io.image.ConvertRaster". I could imagine the issue also to be on my side, i.e. version incompatibilities. In case you do want to take a closer look, a project which replicates this is https://github.com/BernhardWebstudio/DataShot_DesktopApp, while I can also try to reduce it to a runnable "proof-of-warning" if that would help.

**Comment by lessthanoptimal** [comment]
It's just a warning. I was forced to use a hidden API to improve performance by a large amount, like 10x when dealing with swing. At one point I was trying to get the JDK modified to provide low level access to those Rasters but gave up. I should resume that process.

**Comment by lessthanoptimal** [comment]
Leaving this open so that others can see it since I do answer this question on a regular basis.

**Comment by GenieTim** [comment]
Alright, thanks!

**Comment by lessthanoptimal** [comment]
Cleaning up issues.
