### ISSUE TITLE
Build failed executing ./gradlew oneJarBin 

### ISSUE THREAD

**Issue by huangh12** [lessthanoptimal/BoofCV#186]
Hi @lessthanoptimal ,
Following the constructions in readme, I try to build the boofcv project from source.
The boofcv version I used is v0.35 with commit id 9f514cbf014401de89e26c89164a0f9bc4a4dcfd.

I got below error message after executing `./gradlew oneJarBin `

> A problem was found with the configuration of task ':oneJarBin'.
> No value has been specified for property 'archiveFile'.

This seems like a version mismatch between gradle tool and build.gradle. But I can't figure out after many trails.

**Comment by lessthanoptimal** [comment]
I replicated that issue. Most likely Gradle got upgraded and this command was never tested. I checked the latest SNAPSHOT and it's working there. I've not checked v0.36, but if I had to guess it's probably working. Do you need version 0.35 specifically? A test should also be added for these gradle build commands to prevent this from happening again.

**Comment by huangh12** [comment]
@lessthanoptimal Thanks for the reply.  I test v0.36 and v0.36.1 and got following error message
> Execution failed for task ':main:boofcv-types:compileJava'.
> java.lang.ExceptionInInitializerError (no error message)

**Comment by huangh12** [comment]
After several trails, the below error message somehow disappeared. 
> Execution failed for task ':main:boofcv-types:compileJava'.
> java.lang.ExceptionInInitializerError (no error message)

And I finally got the error mentioned at the begining. 
> A problem was found with the configuration of task ':oneJarBin' (type 'Jar').
> No value has been specified for property 'archiveFile'.

v0.35, v0.36 and v0.36.1

**Comment by huangh12** [comment]
@lessthanoptimal  Problem fixed by adding the `archiveFileName` and `destinationDirectory` in `build.gradle` file.
```
...
// Creates a single jar which contains all the subprojects in main and integration
task oneJarBin(type: Jar, dependsOn: javadocProjects.collect { it + ":compileJava" }) {
    baseName = 'BoofCV'
    archiveFileName = 'boofcv.jar'
    destinationDirectory = file("$buildDir/dists")

    from files(javadocProjects.collect { project(it).sourceSets.main.output }) {
        exclude 'META-INF/*.RSA', 'META-INF/*.SF', 'META-INF/*.DSA'
    }
}
...
```
