### ISSUE TITLE
Visual odometry on android

### ISSUE THREAD

**Issue by sieme97** [lessthanoptimal/BoofCV#189]
For visual odometry, what speed (in FPS) I can expect on android?

**Comment by lessthanoptimal** [comment]
BoofCV doesn't have a monocular algorithm which would work on Android yet. That will probably be changing in 2021. Stereo VO gets about 15 fps on a Raspberry PI 3 I think. I suspect if you are using a recent mid to high end Android phone you would be able to easily hit 30+ fps at 800x600 or 640x480 resolution when that feature is added.

**Comment by sieme97** [comment]
Cool, thanks.
