### ISSUE TITLE
I can not find boofcv.io.ffmpeg.FfmpegVideo

### ISSUE THREAD

**Issue by liojx** [lessthanoptimal/BoofCV#190]
in class boofcv.io.video.DynamicVideoInterface, construct method load an inexistence  class ' boofcv.io.ffmpeg.FfmpegVideo'.Where can I get this class?

**Comment by lessthanoptimal** [comment]
Is `boofcv-ffmpeg` in your dependency list?

**Comment by liojx** [comment]
> s `boofcv-ffmpeg`

i'll try.

**Comment by lessthanoptimal** [comment]
I'm assuming that this has been resolved. Feel free to re-open if it hasn't been.
