### ISSUE TITLE
QrCodeDecoderImage: readFormatRegion1 seems to not read one last bit

### ISSUE THREAD

**Issue by DCNick3** [lessthanoptimal/BoofCV#209]
Here it is:
```java
	private boolean readFormatRegion1( QrCode qr ) {
//		if( qr.ppRight.get(0).distance(988.8,268.3) < 30 )
//			System.out.println("tjere");
//		System.out.println(qr.ppRight.get(0));

		// set the coordinate system to the closest pp to reduce position errors
		gridReader.setSquare(qr.ppRight, (float)qr.threshRight);

		bits.resize(15);
		bits.zero();
		for (int i = 0; i < 8; i++) {
			read(i, 8, 6 - i);
		}

		gridReader.setSquare(qr.ppDown, (float)qr.threshDown);

		for (int i = 0; i < 6; i++) {
			read(i + 8, i, 8);
		}

		return true;
	}
```

First, it correctly reads 8 bits from near right finder pattern, but then reads only 6 (instead of 7) bits from the down pattern.

**Comment by lessthanoptimal** [comment]
Fixed! That's a good catch. It went undetected for so long because of the redundancy. You must have been plowing through that code! Added unit tests to prevent that from happening again in the future.

https://github.com/lessthanoptimal/BoofCV/pull/215

**Comment by lessthanoptimal** [comment]
Feel free to reopen if the issue isn't resolved.

**Comment by DCNick3** [comment]
>Fixed! That's a good catch. It went undetected for so long because of the redundancy. You must have been plowing through that code! Added unit tests to prevent that from happening again in the future.

Yeah, just made a [DCNick3/pqrs](https://github.com/DCNick3/pqrs) based on the algorithms used in BoofCV to make it work in web. Not a full-blown port, some corners were cut, but still... Quite cool image processing you've got here =)

Probably should add a notice to the readme

**Comment by lessthanoptimal** [comment]
cool thanks for sharing! Yeah it's good to site your sources. I attempt to do that as much as possible when I "borrow" ideas from other projects.

Out of curiosity, how readable did you find this part of the code?

**Comment by DCNick3** [comment]
>Out of curiosity, how readable did you find this part of the code?

Pretty good, but there, of cause were some issues...

First of all, ISO seems to use a term "finder pattern" for what is code is called "Position Pattern". Was a bit confusing

The way that blocks were split was not clear [(here)](https://github.com/lessthanoptimal/BoofCV/blob/26f5f51e15dd68eeb236d76e397babedcda6933e/main/boofcv-recognition/src/main/java/boofcv/alg/fiducial/qrcode/QrCodeDecoderBits.java#L86). The ISO does not contain specific algorithm for variating the block size, but it was constructed and not commented... At that point in time I kinda lost it and took decoding code from zxing.

There was also [quite complicated algorithm](https://github.com/lessthanoptimal/BoofCV/blob/1a7b9ecb3de749cd6bcea758f5b31425506bbf74/main/boofcv-feature/src/main/java/boofcv/alg/shapes/polyline/splitmerge/PolylineSplitMerge.java) for fitting contour to polygon. Spent quite a long time to grasp its idea, but gave up and copied it almost verbatim =(

Other parts were good, did not have much trouble understanding what was going on

Just as an improvement idea: using local mean for computing the threshold when sampling the QR code yields much better results that just a global threshold value for uneven lighting. Improved performance quite much in my use case (scanning of QR projected to screen in intensively lit room)

**Comment by lessthanoptimal** [comment]
thanks for the feedback! I'll see if I can clean up some of those documentation issues. Some of the documentation I was first looking at also might have been inconsistent between the various drafts. There are also a bunch of algorithms in BoofCV that should have a tech report or conference paper written up for them but i've not done that yet.

The local mean suggestion is good! I'll look into using it. My main worry would be speed, but if it increases accuracy significantly it's probably worth it.
