### ISSUE TITLE
Small Bug in SimpleCamera2Activity

### ISSUE THREAD

**Issue by infologika-outsrc** [lessthanoptimal/BoofCV#216]
Thank you very much for the library. 
There is a small bug in SimpleCamera2Activity.java

In  routine
public void cameraIntrinsicNominal(CameraPinhole intrinsic )

The code:
	// 60 degrees seems reasonable for a random guess
	PerspectiveOps.createIntrinsic(open.mCameraSize.getWidth(),open.mCameraSize.getHeight(),
					UtilAngle.radian(60));

Should be enclosed inside the 

if (open.mCameraCharacterstics != null) {
}

block, and not after it.

Otherwise it crashes occasionally.

**Comment by lessthanoptimal** [comment]
Yep that looks like a bug. It's in the queue to get fixed. Thanks!

**Comment by lessthanoptimal** [comment]
fixed
