### ISSUE TITLE
Why does the QR Code decoder select the wrong encoding when it should pick UTF-8

### ISSUE THREAD

**Issue by gerripeach** [lessthanoptimal/BoofCV#237]
Hello,
I don't know if it's a bug or if I am doing something wrong.
I created a little test programm to reproduce the bug(?).

1. I created a barcode the char `§` in it.
2. The detection result is `�`

Bug or my failure?

The Barcodes:
![1](https://user-images.githubusercontent.com/1677881/111371822-2fcd4780-869a-11eb-96cc-fac1c13b3224.PNG)
![2](https://user-images.githubusercontent.com/1677881/111371825-2fcd4780-869a-11eb-97f5-99e794d00b2f.PNG)

My Code:
```
public class Library {

	public static void main(String[] args) throws FileNotFoundException, IOException {
		Path path = Paths.get("C:\\Users\\Phillip\\Downloads\\Unbenannt.PNG");
		BufferedImage image = ImageIO.read(new FileInputStream(path.toFile()));
		detectQRWithBoofCV(image);
	}

	private static void detectQRWithBoofCV(final BufferedImage bufferedImage) {
		GrayU8 gray = ConvertBufferedImage.convertFrom(bufferedImage, (GrayU8) null);
		QrCodeDetector<GrayU8> detector = FactoryFiducial.qrcode(new ConfigQrCode(), GrayU8.class);

		detector.process(gray);
		List<QrCode> detections = detector.getDetections();

		for (QrCode qr : detections) {
			System.out.println(qr.message);
		}
	}
}
```

**Edit**
* I run openjdk 15.02
* eclipse
* windows 10

**Comment by lessthanoptimal** [comment]
Most likely a string encoding issue. There are multiple locations that could have the wrong string encoding and not all of them are related to BoofCV. When I scanned it on my phone I saw two characters 'A§' which I guess isn't totally correct. You can force the decoder to use a specific encoding:

http://boofcv.org/javadoc/boofcv/factory/fiducial/ConfigQrCode.html#forceEncoding

Your terminal might also not support that encoding, which is why it displays the wrong character.

**Comment by gerripeach** [comment]
You are right. Encoding issue. Thanks for the hint!
It seems to let the library guess it not the best idea for acurate results.
I modified my code to "detect" the right encoding.

```
public class Library {

	public static void main(String[] args) throws FileNotFoundException, IOException {
		Path path = Paths.get("C:\\Users\\Phillip\\Downloads\\1.PNG");
		BufferedImage image = ImageIO.read(new FileInputStream(path.toFile()));
		detectQRWithBoofCV(image);
	}

	private static void detectQRWithBoofCV(final BufferedImage bufferedImage) {
		Map<String, Charset> cs = Charset.availableCharsets();
		for (String key : cs.keySet()) {

			GrayU8 gray = ConvertBufferedImage.convertFrom(bufferedImage, (GrayU8) null);
			ConfigQrCode config = new ConfigQrCode();
			config.forceEncoding = cs.get(key).name();

			QrCodeDetector<GrayU8> detector = FactoryFiducial.qrcode(config, GrayU8.class);
			detector.process(gray);
			List<QrCode> detections = detector.getDetections();

			for (QrCode qr : detections) {
				if (!qr.message.equals("§")) {
					continue;
				}
				System.out.println(qr.message + "   " + cs.get(key).name());
			}
		}
	}
}
```

**Comment by gerripeach** [comment]
@lessthanoptimal I tried the same qr code with the zxing library. At least for UTF8 (which tends to be the correct encoding of my example) zxing does the guessing correct.
I looked up their code, maybe you can improve the guessing with that:

https://github.com/zxing/zxing/blob/master/core/src/main/java/com/google/zxing/common/StringUtils.java#L54

**Comment by lessthanoptimal** [comment]
Interesting. Most of the time it defaults to UTF-8. I assumed it was going to be some bizarre encoding to your local region. I'll look into this to see why it picked the wrong one.

**Comment by gerripeach** [comment]
FYI: I was lazy to write my own qr code generator. So I used the first online qr code generator I could find. Maybe the generator i picked has some issues?

**Comment by lessthanoptimal** [comment]
There is the real possibility that QR code generator is non compliant. I've seen some real bad ones out there. I wish all the scanners didn't include code to handle malformed QR codes because it makes everything run slower.

P.S. There's a command line tool included with BoofCV for generating QR codes. Plus you can do it with just a few lines of code.

**Comment by gerripeach** [comment]
I just wrote a qr code generator with boof cv library. Text: `§` and encoding utf8. I used the example code provided on the website. I let the library (code snippet of the original post) decode it and I got an unkown character again.

for reference "how I generated the qr code"
```
public class ExampleRenderQrCode {
	public static void main(String[] args) {

		QrCodeEncoder encoder = new QrCodeEncoder();
		encoder.setByteCharacterSet(Charsets.UTF_8);
		encoder.setError(QrCode.ErrorLevel.M);
		encoder.addAutomatic("§");

		QrCode qr = encoder.fixate();

		QrCodeGeneratorImage render = new QrCodeGeneratorImage(20);

		render.render(qr);

		BufferedImage image = ConvertBufferedImage.convertTo(render.getGray(), null);
		ShowImages.showWindow(image, "Rendered QR Code", true);
	}
}
```

**Comment by lessthanoptimal** [comment]
cool. should be easy to add a unit test for this situation!

**Comment by gerripeach** [comment]
yep.

if I tell the decoder to use utf8 I get the correct result. If not it fails.

```
		ConfigQrCode config = new ConfigQrCode();
		config.forceEncoding = "UTF-8";

		QrCodeDetector<GrayU8> detector = FactoryFiducial.qrcode(config, GrayU8.class);
```

**Comment by gerripeach** [comment]
I debuged it. `guessEncoding` returns `ISO8859_1`

**Comment by lessthanoptimal** [comment]
https://github.com/lessthanoptimal/BoofCV/pull/240

There was a type-o. The fix was changing it from `v >= 0xC3` to `v >= 0xC2`.  I did some code clean up in that PR, so it looks like a massive change when it is not.

This should merged into SNAPSHOT soon.

**Comment by lessthanoptimal** [comment]
Merged. Feel free to re-open if there is still an issue.
