### ISSUE TITLE
Is there a method to get the Tangential distortion coefficients when calibrating

### ISSUE THREAD

**Issue by esteimle** [lessthanoptimal/BoofCV#239]
Just wondering. I tried to just naively add them into the reported data but they come back 0,0.  So I looked through the code and I only see RadialDistortion running, and not similar looking file for Tangential. Is it just not supported?  Thank you!

**Comment by lessthanoptimal** [comment]
Sorry for taking a bit.  I'm assuming are you looking at ExampleCalibrateMonocular. if you look at line 78 there's a function and you need to change that to:

`calibrationAlg.configurePinhole( true, 2, true);`

The last argument tells it to estimate tangential terms. I'll modify this example to point that out. The code should also be converted to using a Configuration as those are easier to read and more self documenting.

**Comment by lessthanoptimal** [comment]
https://github.com/lessthanoptimal/BoofCV/blob/SNAPSHOT/examples/src/main/java/boofcv/examples/calibration/ExampleCalibrateMonocular.java

Let me know if that modifcation helps clarify.

**Comment by esteimle** [comment]
Thank you
