### ISSUE TITLE
ImageBase is not serializable since its member ImageType does not implement Serializable

### ISSUE THREAD

**Issue by pcmoen** [lessthanoptimal/BoofCV#24]
Serialization of the boofcv.struct.image.ImageBase class throws an java.io.NotSerializableException exception since it's member imageType of type boofcv.struct.image.ImageType is not serializable.

**Comment by lessthanoptimal** [comment]
What's the use case for serializing this object?  It would probably be a very inefficient image format.

**Comment by pcmoen** [comment]
Our use case is transferral of images on a local network. We do this since some of the processing that needs to be done on another computer.

The benefits of compressing the images would be negligible with regards to transfer time. We would rather have the convenience of just passing the object across the wire.

It was serializable in earlier versions. So for us it's regression that would have us change our code.

**Comment by lessthanoptimal** [comment]
Fixed.  Added unit tests for serialization so this shouldn't happen again.

46a501793893ebd74226249f96a1426139309231
