### ISSUE TITLE
Not able to run examples from IDE

### ISSUE THREAD

**Issue by doom369** [lessthanoptimal/BoofCV#25]
Hello,

Just imported project from git with IntelliJ Idea and got compilation error.

FactoryWaveletDaub class uses org.ejml.interfaces.linsol.LinearSolver class which is not present in 

```
      <dependency>
        <groupId>com.googlecode.efficient-java-matrix-library</groupId>
        <artifactId>ejml</artifactId>
        <version>0.24</version>
      </dependency>
```

While later ejml jar version has it. Is it wrong dependency?

**Comment by lessthanoptimal** [comment]
Which version of BoofCV are you using?  That's an older version of EJML.

**Comment by doom369** [comment]
I'm using those one in origin/master. I don't see any other branches in this repo.
Version in POM
```
  <artifactId>boofcv</artifactId>
  <version>0.17-SNAPSHOT</version>
```

Do you have some other repo?

**Comment by lessthanoptimal** [comment]
Remove your dependency on EJML and it should work.

**Comment by doom369** [comment]
It doesn't help. I can fix it by upgrading ejml version. But question is - is that supposed to be like that? If newer version of ejml is used so why older one in dependency? Sorry for annoying =)

**Comment by lessthanoptimal** [comment]
Are you including another library which uses EJML?  0.24 is used by some machine learning library and they haven't updated.

I just checked the build.gradle and everything seems to be correct.
https://github.com/lessthanoptimal/BoofCV/blob/master/build.gradle
It depends georegression, which depends on ddogleg, which depends on EJML.

**Comment by doom369** [comment]
Ok, I'll check locally. Maybe problem with my gradle.

**Comment by lessthanoptimal** [comment]
There might be one issue.  They reference the latest EJML SNAPSHOT which had some how level re factoring that was not reflected in the latest SNAPSHOT.  Working on fixing that now.  Might want to consider using a stable version of BoofCV to avoid stuff like this.

**Comment by lessthanoptimal** [comment]
I've updated all the SNAPSHOTs.  This might fix your issue.  Just as a reminder, SNAPSHOTs are not always updated automatically.  You might need to manually clear your Maven jar cache.
