### ISSUE TITLE
Adding Xuggler back as an integration package under a new maintainer/fork.

### ISSUE THREAD

**Issue by olivierayache** [lessthanoptimal/BoofCV#258]
Hello by looking for media processing libraries, I saw that BoofCV drop the support of Xuggler due to its lack of support. If you are interested I maintain a fork of Xuggler since 2014. 
The project is located here: https://github.com/olivierayache/xuggle-xuggler.
A Cloudsmith repository provides the binaries: https://cloudsmith.io/~olivier-ayache/repos/xuggler.

**Comment by lessthanoptimal** [comment]
Thanks for letting me know it still lives! After Xuggler faded away BoofCV switched to the FFMPEG wrapper in javacpp-presets. Have you done any comparison against that? The main objection to bringing Xuggler integration back in is the cost of maintaining the the integration package. To justify that there needs to be some significant advantage over what's there now. Smaller package size? Faster? API is better for BoofCV? ... Etc.

**Comment by olivierayache** [comment]
Hello I think there are multiple interests using Xuggler for BoofCV:
- Images and audio extracted from video/camera are directly usable in Java (read/write)
- Xuggler has support for Linux/Android/Windows/MacOS and I am working with Kotlin Multiplatform for iOS
- On Android I have implemented HW acceleration for encoding/decoding
- FFmpeg filtering API is supported by my fork. Thanks to that BoofCV could use all FFmpeg filters

**Comment by lessthanoptimal** [comment]
Cleaning up stale tickets and going to close this one. There is no fundamental objecting to adding Xuggler back in, it's just that the javacpp-presets works well enough and also wraps FFMPEG. I don't think it's worth the extra development effort to support both right now. If you created a PR to add it back in and properly tested it, there's a good chance it would be accepted.
