### ISSUE TITLE
Explanation - Degeneracy detection in SFM - uncalibrated MVS

### ISSUE THREAD

**Issue by SbrezVis** [lessthanoptimal/BoofCV#269]
Hi all,
I have noticed that in the android app under structure from motion - uncalibrated mvs, there is a functionality of degeneracy detection that appears in two ways:
a. When I only rotate the phone I get a message saying "Translate! dont just rotate".
b. When I'm sending images to reconsturction when only rotation took place, I get a message saying "metric failed".

1. Can someone please refer me to the code that performs this detections?
2. Can you please briefly explain how this two degeneracy detection algorithms works?

Thanks

**Comment by lessthanoptimal** [comment]
Replied to this question on the message board.

https://groups.google.com/g/boofcv/c/DHaTtYjndnw
