### ISSUE TITLE
Unable to load tiff files

### ISSUE THREAD

**Issue by thhart** [lessthanoptimal/BoofCV#27]
BoofCV fails to load tiff images in MediaManager.
I think it is related to a bug in Java/ImageIO not returning a valid image type when loading tiff files (it is 0).  In DefaultMediaManager there is the member openImage which needs the type to reconstruct an image.
This seems to be a hack already, so I have an additional hack for it:
b.getType() != 0 ? b.getType() : (b.getSampleModel().getNumBands() > 1 ? BufferedImage.TYPE_BYTE_RGB : BufferedImage.TYPE_BYTE_GRAY)

The hack above might break special image color formats which I am not aware of, but works for images I get from GigE sources (color and monochrome). Probably TYPE_BYTE_RGB is to much and an other type might appropriate as default.

The detailed exception:

java.lang.IllegalArgumentException: Unknown image type 0
	at java.awt.image.BufferedImage.<init>(BufferedImage.java:509)
	at boofcv.io.wrapper.DefaultMediaManager.openImage(DefaultMediaManager.java:74)
	at test.BoofLoader.main(BoofLoader.java:19)

**Comment by thhart** [comment]
Additional note, I use the tiff format for image processing as fast as possible. I have attached a sampe tiff image. (it is ended with png, but it is a tiff in fact, attaching tiffs not allowed here) 
![image](https://cloud.githubusercontent.com/assets/2632538/8155024/239dbf86-1340-11e5-8ab8-fec1ac2f038b.png)

**Comment by lessthanoptimal** [comment]
the tiff file you uploaded, it is extremely wide and narrow right?

**Comment by thhart** [comment]
Yes, this is correct. It is 1024x24.

**Comment by lessthanoptimal** [comment]
I'm my system ImageIO.read() just returns null since it doesn't support TIFF.  Do you have some additional software installed?

**Comment by thhart** [comment]
Hi Peter, I apologize, indeed I use the JAI ImageIO 1.1 in my environment. This introduces support for various formats to the standard ImageIO. However it is really bad supported (F** O**), so I really don't know if it is worth to introduce a hack just for this. Please decide yourself and close the issue if you want.

**Comment by lessthanoptimal** [comment]
I'll keep this open for a bit.  If high speed isn't an issue there is a function for converting images using getRGB() which should work no matter what the underlying image format is.
