### ISSUE TITLE
QuadPoseEstimator

### ISSUE THREAD

**Issue by PGRBryant** [lessthanoptimal/BoofCV#29]
getSideLength does not seem to exist within georegression nor elsewhere (lines 168 and 169 of QuadPoseEstimator.java).  

Is there a replacement, or a simple way to get the distance between two corners of a Quadrilateral_F64?

**Comment by lessthanoptimal** [comment]
Your using the latest git code correct?  That's probably caused by the latest snapshot of georegression not reflecting the latest code.  You should be able to fix that by checking out georegression also and doing a "gradle install" on it.  Would do the same for DDogleg to be safe.

**Comment by PGRBryant** [comment]
Interestingly, when I loaded this program into Eclipse, the problem seemed to go away. I first was using android studio, and I had to rewrite a simple distance equation to get it to run correctly. So, issue resolved.

**Comment by lessthanoptimal** [comment]
Try running it again in Android studio out of curiosity.  I might work now since I updated the SNAPSHOT.  Also are you messing around with fiducials?
