### ISSUE TITLE
Null Pointer Exception in PointTrackerKltPyramid

### ISSUE THREAD

**Issue by ericbhatti** [lessthanoptimal/BoofCV#30]
Hey Peter. Great work on this awesome library. I was using the PointTrackerKltPyramid and got a null pointer exception. 

I read the source code, and it looks like you missed an initialization in one of the constructors.

              public PointTrackerKltPyramid(KltConfig config,
								  int templateRadius ,
								  PyramidDiscrete<I> pyramid,
								  ImageGradient<I, D> gradient,
								  InterpolateRectangle<I> interpInput,
								  InterpolateRectangle<D> interpDeriv,
								  Class<D> derivType ) {

		this.config = config;
		this.templateRadius = templateRadius;
		this.gradient = gradient;
		this.basePyramid = pyramid;

		KltTracker<I, D> klt = new KltTracker<I, D>(interpInput, interpDeriv,config);
		tracker = new PyramidKltTracker<I, D>(klt);
	}

You didn't initialize the derivType member variable. The fixed constructor will be:

              public PointTrackerKltPyramid(KltConfig config,
								  int templateRadius ,
								  PyramidDiscrete<I> pyramid,
								  ImageGradient<I, D> gradient,
								  InterpolateRectangle<I> interpInput,
								  InterpolateRectangle<D> interpDeriv,
								  Class<D> derivType ) {

		this.config = config;
		this.templateRadius = templateRadius;
		this.gradient = gradient;
		this.basePyramid = pyramid;

        //// The added line
        this.derivType = derivType;

		KltTracker<I, D> klt = new KltTracker<I, D>(interpInput, interpDeriv,config);
		tracker = new PyramidKltTracker<I, D>(klt);
	}

**Comment by lessthanoptimal** [comment]
You're right.  Was a bit surprised that a simple bug was found in code that old.  Ended up combining those two constructors.  You can now specify null for the detector, but don't expect spawn to work if you do.

83298a91ffc0a561b72cb8efaf4e59db18aa911d

Thanks!
