### ISSUE TITLE
building android aar library

### ISSUE THREAD

**Issue by TheBricktop** [lessthanoptimal/BoofCV#302]
Hello,
is there a known way to build boofCV to android aar library?

**Comment by lessthanoptimal** [comment]
don't see any reason why not, but I've not really looked into it. Any reason including it like a normal jar isn't desirable?

**Comment by TheBricktop** [comment]
That's a valid question, my experience was only with building aar but not including jar libraries, ill check it shortly.

**Comment by G00fY2** [comment]
@TheBricktop aar libraries only offer additional Android specific functionality like declaring permissions, limiting mininum Android SDK version or shipping resources like drawables or xml layouts. I don't see how this library would benefit from using the aar format. :)
