### ISSUE TITLE
missing boofcv.struct.border.ImageBorder_F32.java ?

### ISSUE THREAD

**Issue by outersky** [lessthanoptimal/BoofCV#305]
Class boofcv.struct.border.ImageBorder_F32 is used everywhere, but it can be found nowhere.

why?

**Comment by outersky** [comment]
sorry , I did NOT execute `./gradlew autogenerate`

**Comment by stellarpower** [comment]
Place for the docs to be updated to add this step: [3D Reconstruction Tutorial](https://boofcv.org/index.php?title=3D_Reconstruction_on_Desktop_Tutorial#Building)

**Comment by lessthanoptimal** [comment]
@stellarpower I did update the build instructions, but I also noticed that particular page said you need to build from source. That is no longer true and you can use the precompile Application. The wiki has been updated. Thanks!

**Comment by stellarpower** [comment]
Yup, wish I had read the output more, as it would've saved me a couple of hours trying to build it!! I forgot to add, but seems `SceneReconstructionApp` has been renamed to `SceneReconstruction`, so that should probably go in the docs too. Thanks!

**Comment by lessthanoptimal** [comment]
I've added a sanity check to the build script that checks to see if `autogenerate` was run and prints out saying you need to run it.
