### ISSUE TITLE
ExampleSegmentSuperpixels Fails for FH04 for Attached Image

### ISSUE THREAD

**Issue by pete-experimenter** [lessthanoptimal/BoofCV#31]
Example file https://github.com/lessthanoptimal/BoofCV/blob/master/examples/src/boofcv/examples/segmentation/ExampleSegmentSuperpixels.java for boofcv v0.19 fails with
```
java.lang.IllegalArgumentException: Expected 4 bands in dst not 3
	at boofcv.io.image.ConvertBufferedImage.convertFromMulti(ConvertBufferedImage.java:400)
	at boofcv.io.image.ConvertBufferedImage.convertFrom(ConvertBufferedImage.java:201)
```
when using the below rectangle image for Fh04
![rectangle](https://cloud.githubusercontent.com/assets/6091200/10697953/ef316966-79c7-11e5-84b0-e728b89f0c30.png)

How can this be solved?

**Comment by lessthanoptimal** [comment]
The alpha channel in the input image is messing things up.  I've added a new function ConvertBufferedImage.stripAlphaChannel() to get around this annoying issue.  If you don't want to update to the latest snap shot, here's the function's code:

	public static BufferedImage stripAlphaChannel( BufferedImage image ) {
		int numBands = image.getRaster().getNumBands();

		if( numBands == 4 ) {
			BufferedImage output = new BufferedImage(image.getWidth(),image.getHeight(),BufferedImage.TYPE_INT_RGB);
			output.createGraphics().drawImage(image,0,0,null);
			return output;
		} else {
			return image;
		}
	}

**Comment by pete-experimenter** [comment]
Tested the function - works. Thanks!
