### ISSUE TITLE
Decode transposed QR codes

### ISSUE THREAD

**Issue by lessthanoptimal** [lessthanoptimal/BoofCV#313]
A common problem with encoders is that they mess up coordinate system transforms and generate a QR code where the marker is transposed, making it non-compliant. Add a flag which will enable decoding of these QR codes.

- Add a flag to consider the possibility that the marker is transposed
- Make sure there is no speed regression when the flag is false
- Update example

**Comment by lessthanoptimal** [comment]
Started work on this task

https://github.com/lessthanoptimal/BoofCV/tree/feature/transposed

Only added a new operator to transpose images so far. The actual solution will not sure that operator but seemed like it would be useful anyways.

**Comment by lessthanoptimal** [comment]
https://github.com/lessthanoptimal/BoofCV/pull/325

well that was not too difficult. Doing more tests to make sure there isn't an unintentional consequence. Will merge into SNAPSHOT "soon"

**Comment by lessthanoptimal** [comment]
@wkornewald

**Comment by wkornewald** [comment]
@lessthanoptimal Thanks, that looks good. Maybe we'll still keep our multi-threaded implementation but use the new transpose function underneath, so we can speed up the scan (compared to the default implementation).

**Comment by lessthanoptimal** [comment]
Sounds good. Let me know if there are any issues. Going to close this ticket since I think everything is resolved now.

FYI The latest code now uses NullAway to strictly enforce null checks. I don't think there are any changes which will affect you but I could be wrong as a ton of code got modified. Going to shoot for a new stable release in January or early Feb.
