### ISSUE TITLE
http://www.boofcv.org/javadoc Not Found

### ISSUE THREAD

**Issue by changbaishan** [lessthanoptimal/BoofCV#314]
http://boofcv.org/javadoc
Not Found
The requested URL was not found on this server.

Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.

**Comment by lessthanoptimal** [comment]
thanks for reporting that. Must have gotten messed up when mediawiki got updated.

**Comment by lessthanoptimal** [comment]
fixed
