### ISSUE TITLE
Two step multiview calibration?

### ISSUE THREAD

**Issue by shikui08** [lessthanoptimal/BoofCV#317]
Great work!

Here is what I am trying to figure out when experimenting with Stereo calibration example.  Given two cameras which are distanced from each other(5 meters, for example). it is really difficult to acquire high quality synchronized image pairs to produce good enough intrinsic and extrinsic calibration results. But on the other hand, it is much easier to do intrinsic calibration separately on each camera and getting good result. So if we can provide intrinsics for each camera,  is it of any help when doing extrinsic calibration?  If so, any idea on how to achieve this? Thanks!

EDIT:  Found out that opencv's _stereoCalibrate_ is useful reference on this.

**Comment by shikui08** [comment]
I guess It maybe useful if input images can be specified as  
 1) images for intrinsic calibration of left camera.
 2) images for intrinsic calibration of right camera.
 3) image pairs for evaluating right to left transformation.

Also it would be helpful if we can get reconstructed 3d landmarks of the board in each image-pair. It will make sense if the boards are on the ground and we will get 'real' 3d poses of each camera.

**Comment by lessthanoptimal** [comment]
Hey @shikui08 any reason you closed this? Sorry was meaning to reply earlier.  I suspect that some improvement is needed in the documentation. Internally stereo calibration does first process each camera individually then refines everything all at once. There are plans to have a full multi camera calibration system for n-views and replace the stereo calibration with that system.

When collecting images I tend to focus on images for the left camera, then the right camera, When collecting those images I don't worry about what it looks like in the other camera. Then I'll collect images where the target is clearly visible in both cameras to make sure there's good data for estimating the baseline.

**Comment by shikui08** [comment]
> Hey @shikui08 any reason you closed this? Sorry was meaning to reply earlier. I suspect that some improvement is needed in the documentation. Internally stereo calibration does first process each camera individually then refines everything all at once. There are plans to have a full multi camera calibration system for n-views and replace the stereo calibration with that system.
> 
> When collecting images I tend to focus on images for the left camera, then the right camera, When collecting those images I don't worry about what it looks like in the other camera. Then I'll collect images where the target is clearly visible in both cameras to make sure there's good data for estimating the baseline.

Thanks for your reply! The reason I close this issue is that I find out that it's depends on which scenario I am dealing with, i.e.  'moving cameras' or 'moving board', 

Basically the current stereo demo&application works well in 'moving camera' scenario.
And the process you described in your comment works on a broader basis, and are similar to I am talking about in the previous one. 
And here is my process:
1. Detect landmarks given some groups of images using DetectSingleFiducialCalibration.
2. Use cv2.calibrateCamera to get intrinsics for each camera.
3. Use cv2.stereoCalibrate to get extrinsic between the two cameras.
4. Use cv2.solvePnP to get reconstructed 3d landmarks for each picture-pair used in step 3.

Here is the java code I use in step 1:


<pre>
package export_ecoboard_landmarks_3d;

import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileOutputStream;
import java.io.OutputStreamWriter;
import java.util.ArrayList;
import java.util.List;

import org.apache.commons.io.FilenameUtils;

import boofcv.abst.fiducial.calib.CalibrationPatterns;
import boofcv.abst.fiducial.calib.ConfigECoCheckMarkers;
import boofcv.abst.geo.calibration.CalibrateMonoPlanar;
import boofcv.abst.geo.calibration.DetectSingleFiducialCalibration;
import boofcv.alg.fiducial.calib.ConfigCalibrationTarget;
import boofcv.factory.fiducial.FactoryFiducialCalibration;
import boofcv.io.UtilIO;
import boofcv.io.calibration.CalibrationIO;
import boofcv.io.image.ConvertBufferedImage;
import boofcv.io.image.UtilImageIO;
import boofcv.struct.image.GrayF32;
import georegression.struct.point.Point2D_F64;

/**

 */
public class App {
    protected static String flagName;
    protected static String parameters;
    protected static void splitFlag(String word) {
        int indexEquals = 2;
        for (; indexEquals < word.length(); indexEquals++) {
            if (word.charAt(indexEquals) == '=') {
                break;
            }
        }
        if (indexEquals == word.length())
            throw new RuntimeException("Expected = inside of flag. " + word);
        flagName = word.substring(2, indexEquals);
        parameters = word.substring(indexEquals + 1);
    }

    public static void main(String[] args) throws Exception {
        try {
            String format = null;
            int nThreads = 8;
            List<String> outputDirs = new ArrayList<>();
            List<String> inputPatterns = new ArrayList<>();
            for (int index = 0; index < args.length; index++) {
                String arg = args[index];
                if (!arg.startsWith("--")) {
                    throw new RuntimeException("Expected flags for chessboard. Should start with '--'");
                }
                splitFlag(arg);
                if (flagName.compareToIgnoreCase("Format") == 0) {
                    format = parameters;
                } else if (flagName.compareToIgnoreCase("OutputDir") == 0) {
                    outputDirs.add(parameters);
                } else if (flagName.compareToIgnoreCase("InputPattern") == 0) {
                    inputPatterns.add(parameters);
                } else if (flagName.compareToIgnoreCase("NThreads") == 0) {
                    nThreads = Integer.parseInt(parameters);
                } else {
                    throw new Exception();
                }
            }
            if (outputDirs.size() != inputPatterns.size())
                throw new Exception("");
            final double squareSize = 1;
            ConfigCalibrationTarget configTarget = new ConfigCalibrationTarget();
            configTarget.type = CalibrationPatterns.ECOCHECK;
            configTarget.ecocheck = ConfigECoCheckMarkers.parse(format, squareSize);
            for (int j = 0; j < outputDirs.size(); j++) {
                String outputDir = outputDirs.get(j);
                String inputPattern = inputPatterns.get(j);
                List<String> imagePaths = UtilIO.listSmartImages(inputPattern, true);
                String landmark_outputDirectory = new File(outputDir, "output_landmarks").getAbsolutePath();
                new File(landmark_outputDirectory).mkdirs();
                int I = 0;
                while (I < imagePaths.size()) {
                    List<Thread> threads = new ArrayList<Thread>();
                    for (int i = I; i < Math.min(I + nThreads, imagePaths.size()); i++)
                        threads.add(new Thread(new Worker(configTarget, imagePaths.get(i), landmark_outputDirectory)));
                    for (Thread t : threads)
                        t.start();
                    for (Thread t : threads)
                        t.join();
                    I = Math.min(I + nThreads, imagePaths.size());
                }
                final DetectSingleFiducialCalibration detector = FactoryFiducialCalibration.genericSingle(configTarget);
                OutputStreamWriter w = new OutputStreamWriter(new FileOutputStream(new File(outputDir, "board3d.txt")));
                for (Point2D_F64 p : detector.getLayout()) // lint:forbidden ignore_line
                    w.write(p.x + " " + p.y + " " + 0 + "\n");
                w.close();
                System.out.println("Saved to " + new File(outputDir, "board3d.txt").getAbsolutePath());
            }
            System.exit(0);
        } catch (Exception e) {
            System.out.println("");
            System.out.println("  --Format=<String>            ");
            System.out.println("  --OutputDir=<String>          ");
            System.out.println("  --InputPattern=<String>       ");
            System.out.println("  --NThreads=<int>              ");
            throw e;
        }
    }

}

class Worker implements Runnable {
    ConfigCalibrationTarget configTarget;
    String imgPath;
    String landmark_outputDirectory;

    public Worker(ConfigCalibrationTarget configTarget, String imgPath, String landmark_outputDirectory) {
        this.configTarget = configTarget;
        this.imgPath = imgPath;
        this.landmark_outputDirectory = landmark_outputDirectory;
    }

    @Override
    public void run() {
        final DetectSingleFiducialCalibration detector = FactoryFiducialCalibration.genericSingle(configTarget);
        final CalibrateMonoPlanar calibrationAlg = new CalibrateMonoPlanar(detector.getLayout());
        calibrationAlg.configurePinhole(true, 2, true);
        File f = new File(imgPath);
        final BufferedImage buffered = UtilImageIO.loadImage(imgPath);
        if (buffered == null) {
            System.err.println("Failed to open 'image' file: " + imgPath);
            return;
        }
        GrayF32 image = ConvertBufferedImage.convertFrom(buffered, (GrayF32) null);
        if (detector.process(image)) {
            CalibrationIO.saveLandmarksCsv(f.getPath(), detector.getClass().getSimpleName(),
                    detector.getDetectedPoints(),
                    new File(landmark_outputDirectory, FilenameUtils.getBaseName(f.getName()) + ".csv"));
        }
        System.out
                .println("Write: " + new File(landmark_outputDirectory, FilenameUtils.getBaseName(f.getName()) + ".csv")
                        .getAbsolutePath());
    }
}


</pre>

I can tell that ECoBoard landmark detection works great.
 
And please feel free to reopen this issue if needed.
