### ISSUE TITLE
Max features suppression method

### ISSUE THREAD

**Issue by thhart** [lessthanoptimal/BoofCV#341]
I have a project in which I have to limit feature extraction to specific amount of features. I am wondering what the default suppression method is? For my use case I would prefer an optimal distribution over the whole image if possible.

**Comment by lessthanoptimal** [comment]
There are a few options for how to do that. I just added an example that visualizes different selection methods

[ExampleFeatureLimit](https://github.com/lessthanoptimal/BoofCV/blob/SNAPSHOT/examples/src/main/java/boofcv/examples/features/ExampleFeatureLimit.java)

There's also the original non-maximum example

[ExampleNonMaximumSuppression](https://github.com/lessthanoptimal/BoofCV/blob/SNAPSHOT/examples/src/main/java/boofcv/examples/features/ExampleNonMaximumSupression.java)

**Comment by lessthanoptimal** [comment]
Cleaning up tickets. I'm assuming those examples are enough.
