### ISSUE TITLE
Error:(21, 34) java: package georegression.struct.point does not exist

### ISSUE THREAD

**Issue by AllanChen** [lessthanoptimal/BoofCV#35]
i can not download georegression version 9.0 , i can not run this project 
```
Error:(21, 34) java: package georegression.struct.point does not exist
```

```
Error:(23, 27) java: package org.ddogleg.sorting does not exist
```

**Comment by lessthanoptimal** [comment]
Cleaning up issues and noticed that this one was missed.  Is this still an issue?  For future reference please state the version of BoofCV that you're using.  I'm guessing that this was a SNAPSHOT and the problem was only temporary.
