### ISSUE TITLE
Maven can't find 0.40.1, even via https://jitpack.io

### ISSUE THREAD

**Issue by rwperrott** [lessthanoptimal/BoofCV#358]
0.40.1 is definitely not on Maven Central (only up to 0.26 at 2016-12-08 03:52),  and no jar files were released here for 0.40.1, so I can't even use this workaround:
```xml
<repository>
   <id>jitpack.io</id>
   <url>https://jitpack.io</url>
</repository>
```

Only personal Maven projects, or private forks of other project, should need to be built and installed locally; everything else should be in a public repo, or at least release jars in their GitHub repo; like here for BootCV.

**Comment by lessthanoptimal** [comment]
A long time ago the package names changed, which explains the confusion. A Gradle example for how to include it can be found in the [readme ](https://github.com/lessthanoptimal/BoofCV#adding-to-gradle-and-maven-projects)or in the [download ](https://boofcv.org/index.php?title=Download)page.

This search on Maven Central seems to bring up the correct jars:

https://search.maven.org/search?q=g:org.boofcv

Does this fix the issue?

**Comment by rwperrott** [comment]
Thanks, that worked.
