### ISSUE TITLE
can not download georegression v9.0

### ISSUE THREAD

**Issue by AllanChen** [lessthanoptimal/BoofCV#36]
I use georegression 8.0 on gradle like 
```
compile group: 'org.georegression', name: 'georegression', version: '0.8'
```
i can download this lib but can not run, because ddogleg have not ```output.setTo ``` Method , just have ```output.set``` i use ddogleg v0.7

**Comment by lessthanoptimal** [comment]
trying to get the 0.19-SNAPSHOT running right?  I updated the SNAPSHOTS of ddogleg and georegression so the automatic download "should" work.  You might need to clear you cache first.  Alternatively you can checkout both of those libraries on github and "gradle install" them locally

**Comment by AllanChen** [comment]
@lessthanoptimal Thank you for your response. I can run your project and demo , that is cool . BTW i have sample question. can i use boofcv mix image like [this](http://www.learnopencv.com/seamless-cloning-using-opencv-python-cpp/) ??

**Comment by lessthanoptimal** [comment]
You're welcome!  Sorry no "seamless cloning" in BoofCV.  Whoever wrote that tutorial on OpenCV must be seriously bad a Photoshop.  No way it would take half a day to crop the airplane!

**Comment by AllanChen** [comment]
@lessthanoptimal No way i can combine two image with boofcv ?

**Comment by lessthanoptimal** [comment]
The built in ways are basically cut and pasting one image into another,  There are tools for combining images together by applying a distortion then pasting it.  There's nothing built in to automatically remove the background and adjust the coloration automatically.  BoofCV probably has most of the tools you would need to implement an algorithm like that but it would take some effort.
