### ISSUE TITLE
Micro QR Codes don't ignore malformed padding

### ISSUE THREAD

**Issue by simon-staal** [lessthanoptimal/BoofCV#397]
This is (most likely) just a repeat of lessthanoptimal/PyBoof#23, except with microQR codes instead of full sized ones. It might be worth ignoring the padding bits for the microQR code detector as well? Although there are relatively few open source micro-QR code libraries which can be compared to, [this online version](https://products.aspose.app/barcode/recognize/qr#/recognized) is able to handle the mispadded codes correctly, as well as [zxing-cpp](https://github.com/zxing-cpp/zxing-cpp).

Other than all the bad 4-digit QR codes produced `segno`, I'm sure you'll be pleased to know that your detector didn't have any issues with payloads in the $[0, 10^6]$ range.

**Comment by simon-staal** [comment]
![1000](https://github.com/lessthanoptimal/BoofCV/assets/59866784/93f74d7d-ef56-4274-81c5-9adaa939c9fb)
Here's an example of the failing codes with the value `1000`

**Comment by lessthanoptimal** [comment]
You're probably right since QR and Micro QR share a bunch of code. Hopefully will have time next week to apply the "fix"

**Comment by lessthanoptimal** [comment]
Latest SNAPSHOT has the fix. Verified that it can now decode that marker. Thanks!
