### ISSUE TITLE
Wavelet Transform applied to an BufferedImage

### ISSUE THREAD

**Issue by RenanFucci** [lessthanoptimal/BoofCV#40]
Hello!
First i would like to congratulate the lib, it helped me a lot!
But I'm having a trouble using wavelet transform in an image Java. I tried specifically the Haar and Daubechies transform.
Could you give a code example of how doing it to a bufferedImage, since the reading to writing?

Thank you!

**Comment by lessthanoptimal** [comment]
You'll need to convert the BufferedImage into a BoofCV type image, which is very easy.  ConvertBufferedImage.convertFrom() to go from BufferedImage to your desired BoofCV image type and ConvertBufferedImage.convertTo() to go back from the BoofCV type to BufferedImage.

For future reference, post question like this (or any follow up questions) to the discussion group.

https://groups.google.com/forum/#!forum/boofcv
