### ISSUE TITLE
FactoryOrientation.sift method doesn't accept null pointer as a configuration

### ISSUE THREAD

**Issue by pcmoen** [lessthanoptimal/BoofCV#44]
The `FactoryOrientation.sift` factory method doesn't accept a null pointer as the configuration. This looks like a oversight when comparing it to the `FactoryOrientationAlgs.average_ii`and `FactoryOrientationAlgs.sliding_ii` methods. Both of these methods will use a default configuration if a null pointer is passed. The `boofcv.alg.feature.orientation.BenchmarkOrientation` test expects the factory method to accept a null pointer and fails to run because of this.

**Comment by lessthanoptimal** [comment]
Thanks!  fixed in 335fa9474fa7d3e437571328324fa1b45fa590b8
