### ISSUE TITLE
xuggler cannot be resolved

### ISSUE THREAD

**Issue by antonkulaga** [lessthanoptimal/BoofCV#49]
Here is what I get: 
 xuggle#xuggle-xuggler;5.4: not found

**Comment by lessthanoptimal** [comment]
Google took down Xuggler's repository and the library is more dead than it was before.  The latest SNAPSHOT has fixed this problem by switching to JavaCV for video play back.

To get the previous stable release to compile again you will need to remove it from settings.gradle then hunt down references in build.gradle too.

**Comment by lessthanoptimal** [comment]
resolved in 0.24
