### ISSUE TITLE
Where is boofcv.alg.color.ColorRgb?

### ISSUE THREAD

**Issue by pacozaa** [lessthanoptimal/BoofCV#50]
I can't find this package according to this [example](http://boofcv.org/index.php?title=Example_RGB_to_Gray)

**Comment by lessthanoptimal** [comment]
import boofcv.alg.color.ColorRgb;  doesn't work?  Could you describe how you are including BoofCV in your project?

**Comment by lessthanoptimal** [comment]
no follow up and it appears to be exactly where it should be
