### ISSUE TITLE
FancyInterestPointRender.addString is a No-Op

### ISSUE THREAD

**Issue by R-Gerard** [lessthanoptimal/BoofCV#51]
The `addString` method in `FancyInterestPointRender` performs a no-op. Should this method be deprecated?

https://github.com/lessthanoptimal/BoofCV/blob/335fa9474fa7d3e437571328324fa1b45fa590b8/main/visualize/src/boofcv/gui/feature/FancyInterestPointRender.java#L75-L81

**Comment by lessthanoptimal** [comment]
It does something now.  Thanks for reporting this.
