### ISSUE TITLE
[minor] Latest tagged version != actual version

### ISSUE THREAD

**Issue by malcolmgreaves** [lessthanoptimal/BoofCV#52]
I spotted a minor discrepancy in version # and git tags.

The latest tagged version (in github) is `v0.14.1`. However, on maven central, and in this project's README, the latest version is `0.24.1`. I believe that the `v0.14.1` tag should be renamed to `0.24.1`.

**Comment by lessthanoptimal** [comment]
Fixed!  Thanks for reporting this and sorry for taking so long to fix it.

**Comment by malcolmgreaves** [comment]
No worries! Thank you for the fix! I am really enjoying boof-cv. It's a life saver compared to using open-cv through JNI! =D =D =D
