### ISSUE TITLE
TemplateMatching: support images wider or taller than 16k pixels

### ISSUE THREAD

**Issue by voxoid0** [lessthanoptimal/BoofCV#53]
Which translates to, use Point2D_I32 instead of Point2D_I16. Also it should check the image width/height that it is within the bounds of the supported size. When I tried to use a 32k+ wide image, i was getting out-of-bounds errors for when it found a template at around -32k; I then figured out it was because the X greater than 2^15 was getting wrapped around in the signed 16-bit int.

**Comment by lessthanoptimal** [comment]
That would be simple to fix by using an int.  However template matching is very slow...

**Comment by lessthanoptimal** [comment]
I'm closing this issue since I think template matching on images that large is just impractical.  Anyone should feel free to re-open this issue if they feel otherwise.
