### ISSUE TITLE
Template matching.  Filtering out false positives

### ISSUE THREAD

**Issue by jipalacio** [lessthanoptimal/BoofCV#55]
Hi, I am new to BoofCV. I use the Template Matching function in BoofCV, but i have a problem.
When my image not contain the template the result list return always one result, It correct?.

**Comment by jigsshah** [comment]
Hello jipalacio,
I am too new to BoofCV. I too have the same issue like you, if you find the solution please let me know.

**Comment by lessthanoptimal** [comment]
You can use the score to filter out false positives.  Here's how you do it.  have a few image examples with good matches.  Look at Match.score.  Now run it with images with no match.  Look at the best score in that.  Hopefully there is a big separation between the two.  If that's the case you can simply select a value and toss out matches.  Keep in mind that the meaning of score is method dependent.

**Comment by lessthanoptimal** [comment]
BTW if you guys know of a library which has a better design for handling this issue let me know.

**Comment by lessthanoptimal** [comment]
Closing issue because there is a known solution and lack of discussion for alternatives
