### ISSUE TITLE
NonMaxCandidates should also work for rectangles

### ISSUE THREAD

**Issue by thhart** [lessthanoptimal/BoofCV#58]
Currently the NonMaxCandidates are working with a radius, so width and height are always equal, it would be nice to be able to specify width and height of the interest separately.

**Comment by thhart** [comment]
I checked the source and I saw by default NonMax "only" works pixel wise, my request was rather related to area maximum search but might also related to pixel max of course.

**Comment by lessthanoptimal** [comment]
Just checked the source code too.  There is no fundamental reason for it to be square and there's unlikely to be any performance hit by making it more flexible either.  However, so much of the library's code touches it refactoring and re-testing is a significant undertaking.  

1) What's the application which requires this modification?
2) Not sure I understand your second comment.  I guess you aren't searching for an local maximum intensity pixel?

**Comment by thhart** [comment]
1. My source images are not equal in dimensions, but more important my structures I am looking for are not equal too. Also I could imagine to be able to find the maximum along an axis.
2. No, I am searching for an local maximum area (blob), I can not use edges easily, is there such a functionality already? Of course I could scale my input down but I am not sure if this is the best way.

**Comment by thhart** [comment]
I have found a suitable solution:
I scale the input up to have the same dimensions for my target, then I can blur the radius and get my blobs extracted also as local maximum points.

**Comment by lessthanoptimal** [comment]
If you're looking for blobs there might be something already there for you.  Have you tried SURF or SIFT detectors?  Plus you can check out a very recently added features.

1) checkout latest SNAPSHOT
2) cd boofcv
3) gradle demonstrations
4) java -jar demonstrations/demonstrations.jar
5) Expand and run feature/DetectFeaturePointSO  select SURF or SIFT. 

Unfortunately this demonstration hasn't been updated to the latest code and doesn't easily let you select a new image.  you will need to modify the source code for that, but it's an easy mod.
