### ISSUE TITLE
Show Source Code in Example Application + Other

### ISSUE THREAD

**Issue by lessthanoptimal** [lessthanoptimal/BoofCV#61]
For this task several simple usability enhancements are requested for the example and demonstration applications, which are written using Swing and share a common code base.  None of the requested improvements are technically difficult for those familiar with Swing and you’re encouraged to ask questions if not sure how to complete a task. 

For details see the [Google Doc](https://docs.google.com/document/d/1bH6hpkrep1v4bsf6B-fytq9ylhCnIyPgRrtXvC5J-50/edit?usp=sharing)

For amount of bounty see http://boofcv.org/index.php?title=Bounties

**Comment by jmankhan** [comment]
Merged #68
