### ISSUE TITLE
sun.awt.image.ByteInterleavedRaster gone in Java 9?

### ISSUE THREAD

**Issue by andrewbaxter** [lessthanoptimal/BoofCV#62]
First of all, thanks for this library!

I'm getting this with Java 9 early access:
```
Exception in thread "main" java.lang.IllegalAccessError: class boofcv.io.image.ConvertBufferedImage (in unnamed module @0x53ce1329) cannot access class sun.awt.image.ByteInterleavedRaster (in module java.desktop) because module java.desktop does not export sun.awt.image to unnamed module @0x53ce1329
	at boofcv.io.image.ConvertBufferedImage.convertFrom(ConvertBufferedImage.java:389)
	at boofcv.io.image.ConvertBufferedImage.convertFromSingle(ConvertBufferedImage.java:295)
```

**Comment by andrewbaxter** [comment]
Not sure if it helps but this compiles in Java 9:
```
byte[] pixels = ((DataBufferByte) bufferedImage.getRaster().getDataBuffer()).getData();a
```
(http://stackoverflow.com/questions/6524196/java-get-pixel-array-from-image)

and
```
bufferedImage.getRaster().getNumBands();
((ComponentSampleModel)bufferedImage.getRaster().getSampleModel()).getScanlineStride();
```
etc

**Comment by andrewbaxter** [comment]
Actually, now I can't compile due to references to missing classes
```
ByteInterleavedRaster
IntegerInterleavedRaster
ShortInterleavedRaster
SunWritableRaster
```
I made shims and switched to the slow converters and everything's working for the moment.

**Comment by lessthanoptimal** [comment]
I really hope they didn't remove those classes.... 

Is the open jdk or oracle jdk?  There are some differences in internal classes.

**Comment by andrewbaxter** [comment]
Oracle JDK 9b158-1.  I don't see them around in this clone at least: https://github.com/netroby/jdk9-dev/tree/1f1e32c62957fac471fd49c4d597706cba281e6f/jdk/src/java.desktop/share/classes/java/awt/image

**Comment by andrewbaxter** [comment]
Oh, they still seems to be here: https://github.com/netroby/jdk9-dev/tree/1f1e32c62957fac471fd49c4d597706cba281e6f/jdk/src/java.desktop/share/classes/sun/awt/image

**Comment by andrewbaxter** [comment]
It's possible there's a jvm command line override to access the package: http://stackoverflow.com/questions/41265266/how-to-solve-inaccessibleobjectexception-unable-to-make-member-accessible-m

**Comment by lessthanoptimal** [comment]
Still not ideal, but looking at your second comment I think there might be a workaround.  Worst case scenario I'll have to create an implementation specific for JDK.  

The reason for all this code accessing stuff it shouldn't is because BufferedImage is poorly designed from an efficiency perspective.  As long as I can get access to the raw array and know the format it's encoded in this should be fast.

**Comment by lessthanoptimal** [comment]
Looked into this issue some more.  Figured out how to  still get access to the raw data.  Unfortunate I have yet to figure out to get the data offset value.  This means support for subimages will most likely be removed.

**Comment by lessthanoptimal** [comment]
I'm attempting to convince the developers of java 9 to change the api. Sounds like I missed the boat for the first release but maybe in a future update.

**Comment by lessthanoptimal** [comment]
Removed all references to internal sun raster classes. Should run in Java 9. Won't work with subimages in java 9
