### ISSUE TITLE
Changed method name in VisualizeBinaryData?

### ISSUE THREAD

**Issue by orfgen** [lessthanoptimal/BoofCV#65]
Hi,

first of all: Thanks for the great library!

In the Canny Edge Example (http://boofcv.org/index.php?title=Example_Canny_Edge), the example code uses the method VisualizeBinaryData.renderExternal, which I found neither in the 0.26 release nor in the snapshot. I guess it was changed to VisualizeBinaryData.render at some point.

**Comment by lessthanoptimal** [comment]
Yep you're right.  I just fixed it.  Thanks! Been trying to figure out some way to automate updating these examples.
