### ISSUE TITLE
Exception in VisualizeBinaryData.render relating to colors

### ISSUE THREAD

**Issue by orfgen** [lessthanoptimal/BoofCV#66]
Hi,
the method render(List<Contour> contours , int colors[] , BufferedImage out) assumes that the provided contours are numbered from 1 to contours.size().
This results in an ArrayIndexOutOfBoundsException if this is not the case:
```
List<Contour> contours = new ArrayList<>();
		
Contour c = new Contour();
c.id = 5;
contours.add(c);
	
BufferedImage image = new BufferedImage(512, 512,BufferedImage.TYPE_INT_RGB);
VisualizeBinaryData.render(contours, (int[]) null, image);
```
Is this intended behavior? If not, I propose similar behavior to two of the renderContours methods:
Instead of using
```
int color = colors[c.id-1];
```
to look up the color increment the index:
```
int index = 0;
  for( Contour c : contours ) {
    int color = colorExternal[index++];
    ...
```

**Comment by lessthanoptimal** [comment]
If I remember correctly, the original idea behind using c.id for the color was to maintain the color for a contour even after other contours had been pruned.  If it was based off of the array order then the colors would swap around making it harder to see what's changed.

Besides improving the JavaDoc, got any more intuitive ideas?  I guess a hash table could be used instead.  Annoys me how much slower that would be, but I doubt the slow down would be noticeable in most applications.

**Comment by orfgen** [comment]
The easiest way would be to create an array of colors of size max{id}. Which is not very memory efficient if you want to show contour number 15083.
The slightly optimized version of this creates an array without initializing it, instead creating a random color for every time we want to retrieve a color and get a 0.

How about a (computationally) cheap hash function that turns the index into a color? Surly some ANDs and XORs are similarly cheap to memory access.

But generally, I don't think that speed is an issue here. I would assume that most people use these colors mostly for debugging purposes or some intermediate result visualization.

**Comment by lessthanoptimal** [comment]
this got changed to 0 to N-1
