### ISSUE TITLE
HOG => Line extraction => Contour

### ISSUE THREAD

**Issue by thhart** [lessthanoptimal/BoofCV#72]
First of all thanks for the great HOG implementation which is performing very well. As always when you start a feature more requests will come, so here it is:
I have a problem where I need a line estimation based on the HOG field. It sounds simple in the beginning but can become tricky in detail. I will see if I can contribute but I am afraid there is no easy approach. But IMHO this would be a great enhancement.

**Comment by lessthanoptimal** [comment]
Can you explain a little bit more?  Like you match a HOG feature and you want the line's slope there?
I've also been meaning to make the HOG API a bit easier to use.  Was planning on doing that after I add a face detector based on it.

**Comment by thhart** [comment]
I know how to extract the slope of a HOG cell, a line is to be defined as the connection between neighbor hog cells with equal (or similar) slope (regression). Of course this can only achieved in the resolution of the hog cell grid.

**Comment by lessthanoptimal** [comment]
Ok I understand what you're up to.  You might be able to use a canny like algorithm or existing code for that.

**Comment by thhart** [comment]
IMHO the HOG information has a new type of quality which is different than classic edge extraction, I see it as an enhancement over the standard algorithms.

**Comment by lessthanoptimal** [comment]
Any update? Considering closing the issue

**Comment by thhart** [comment]
Hi Peter, I have no urgent use for it either now, it was simply and idea, so I will close.
