### ISSUE TITLE
RefineCornerLinesToImage.refine takes in an unused parameter

### ISSUE THREAD

**Issue by Carpetfizz** [lessthanoptimal/BoofCV#73]
[This function](https://github.com/lessthanoptimal/BoofCV/blob/8567948d63f5e2f0868a381ec0f86573670ed12c/main/boofcv-feature/src/boofcv/alg/shapes/polygon/RefinePolygonCornersToImage.java#L117) takes in `Polygon2D_F64 input` but it is not used within the function.

**Comment by lessthanoptimal** [comment]
That's actually done because the interface it implements RefineBinaryPolygon requires it.  That bit of excessive code let's you use swap between algorithms with ease.  Just double checked and RefinePolygonLineToImage does use that parameter.

Thanks for pointing it out though!
