### ISSUE TITLE
[Feature Request] Mean and variance calculation speedup for GrayU8 and GrayU16

### ISSUE THREAD

**Issue by orfgen** [lessthanoptimal/BoofCV#76]
Hi everyone,
I speeded up the calculation of mean and variance for GrayU8 and GrayU16 a bit using histograms.
The original calculations are generated, I will therefore provide a link instead of a pr:
https://github.com/orfgen/BoofCV-misc/tree/master/ImageStatistics-speedup

Regarding the code generation, I will add a second issue for that.

Best regards,
Marius

**Comment by lessthanoptimal** [comment]
Thanks.  Something like this should make it into the next release.  I'm holding off on doing it now depending on the other discussion involving a new auto code generation process.

**Comment by lessthanoptimal** [comment]
Going to table this until after the next release.

**Comment by lessthanoptimal** [comment]
integrated into current SNAPSHOT
