### ISSUE TITLE
[Idea] StringTemplate library for code generation

### ISSUE THREAD

**Issue by orfgen** [lessthanoptimal/BoofCV#77]
Hi,
I looked around for an alternative to the current code generation approach in BoofCV.
After writing a third of a code generator myself and looking at more or less complex libraries, I found 
StringTemplate, which seems to do a good job (even if it is a bit restricted for my personal taste).

I experimented with the min() methods in ImageStatistics, the results can be seen here:
https://github.com/orfgen/AutocodeAlternative

Templates are in /templates, generated java file in /generated.
MinTest.java more or less only invokes the generator.

What do you think? Would it be worth the effort to switch over? I'd be happy to help.

Best regards,
Marius

**Comment by lessthanoptimal** [comment]
Thanks for looking into this!  I like parts of  StringTemplate and don't like others.  The code is more compact.  In some ways it's more readable in other's it's not.  It would be better if the code more closely resembled Java, e.g. no need for \<.

Would be neat if you could pass in the image type to the template code generator then inside the template text have like IMG_TYPE_A for the first image type.  Then automatically recognize array accesses. If it's unsigned swap in & 0xFF.  

```
SUM_TYPE_A example( IMG_TYPE_A img ) {
    return img.data[i];
}
int example( GrayU8 img ) {
    return (img.data[i] & 0xFF);
}
```

**Comment by orfgen** [comment]
Hello Peter,
my idea behind StringTemplate was that we have all information required for the generation in one file. This might work, but the resulting template code does not look very readable.

Based on your feedback, I propose for each class to be generated:
- one generator .java file
- one or more template files containing %PLACEHOLDERS%

I further propose a set of standard placeholders (e.g. %IMAGETYPE%, %UNSIGNED%) to make the template files easier to read. For the special cases that inevitably creep up, the .java file would contain appropriate methods to create custom placeholders.

Since one main purpose of the code generation is to create variants of the same method, we need some kind of "block" construct that allows us to specify that a block of code should be repeated using different combinations of placeholders.
In the simplest form, this could look like this:
```
public class SomeClass {
// BEGIN_BLOCK
public void aMethod(%IMAGETYPE% input) {
	[...]
}
// END_BLOCK
[...]
}
```
It might make sense to actually specify the dimensions that are used to create the combinations, but that rapidly approaches something we need a real parser for:
```
public class SomeClass {
// BEGIN_BLOCK(NUM_BITS={"8", "16"}, CUSTOMPLACEHOLDER={"byte", "char", "int"})
public void anotherMethod(GrayU%NUM_BITS% input, %CUSTOMPLACEHOLDER% value) {
	[...]
}
// END_BLOCK
[...]
}
```
I have created an example implementation of the idea, which can be found at https://github.com/orfgen/Autocode2

About the automatic array recognition/unsigned conversion:
The current approach could be extended this way, but we would either have to roll our own variable scoping or do some reflection with the freshly generated code.
This sounds like requiring some effort, I therefore propose adding it at a later time.

Best regards,
Marius

**Comment by lessthanoptimal** [comment]
Just letting you know that I haven't forgotten about this task. I like the new proposal more. There probably needs to be a bit more intelligence to it. When code is generated, some times its one type per generated class file and other times it's multiple types for functions inside a single file. Some times you need completely different code with only a little bit of overlap, e.g. ints and floats. The last case we can probably ignore for now.

Maybe something like %VARIABLE_NAME[TYPE]% where the string inside of [] determines what type of information is printed out. In this case type would print GrayU8 if it's an image. %VARIABLE_NAME[MASK]% could print out &0xFF or %VARIABLE_NAME[BITS]% would be 8.

**Comment by lessthanoptimal** [comment]
Maybe a Kotlin DSL would work nicely here. I think if it was designed properly IntelliJ might be able to handle updating variables when stuff is refactored.

**Comment by lessthanoptimal** [comment]
Closing this old issue. No longer looking to swap in another way to generate code since it doesn't seem to be worth the effort.
