### ISSUE TITLE
2 errors in every example runing

### ISSUE THREAD

**Issue by ZaharAd** [lessthanoptimal/BoofCV#78]
> Error:(61, 35) java: method localSquare in class boofcv.alg.filter.binary.GThresholdImageOps cannot be applied to given types;
  required: T,boofcv.struct.image.GrayU8,int,double,boolean,T,T
  found: T,boofcv.struct.image.GrayU8,int,double,boolean,T,boofcv.struct.image.ImageGray
  reason: inference variable T has incompatible bounds
    equality constraints: T
    lower bounds: boofcv.struct.image.ImageGray,T

> Error:(124, 61) java: method createPixelPL in class boofcv.factory.interpolate.FactoryInterpolation cannot be applied to given types;
  required: boofcv.alg.interpolate.InterpolatePixelS<T>
  found: boofcv.alg.interpolate.InterpolatePixelS<T>
  reason: inferred type does not conform to upper bound(s)
    inferred: T
    upper bound(s): boofcv.struct.image.ImageGray<T>,boofcv.struct.image.ImageGray<T>

what can I do to fix this?

**Comment by lessthanoptimal** [comment]
What environment are you trying to build this in?  What commands are you using?  Which version of BoofCV are you building?

**Comment by ZaharAd** [comment]
I use IntelliJ, it was an error of independence,
Thanks!
