### ISSUE TITLE
Unable to measure real world dimension

### ISSUE THREAD

**Issue by Zumbalamambo** [lessthanoptimal/BoofCV#79]
How do i measure real world dimensions of objects using BoofCV?

**Comment by lessthanoptimal** [comment]
That's actually a fairly involved high level question. Here's a good place to start learning about the techniques you can use.

https://github.com/Tesla-SCA/quirc_x/blob/regression-test/test_detection_regression.c

Many of the techniques discussed in that book are available in BoofCV.

**Comment by Zumbalamambo** [comment]
Please update the url
