### ISSUE TITLE
DescribeDenseHogFastAlg.getCell((row) y, (col) x) is irritating

### ISSUE THREAD

**Issue by thhart** [lessthanoptimal/BoofCV#80]
I know it might be a bit picky but I stumbled about the order of the arguments. I don't know the reason for this but I recommend to have a stringent order of the arguments as always in image processing (x,y) (col, row). I understand it should not be changed any more because it might break code, it is only meant as a future suggestion, so this issue can be closed easily.

**Comment by lessthanoptimal** [comment]
So there are two competing standards at work. Pixels in an image are column row and elements in a matrix are row column.Yeah in this case it probably should have used the pixel notation. I'll make a note.
