### ISSUE TITLE
[Feature Request] Standalone Demonstration and Example Application

### ISSUE THREAD

**Issue by lessthanoptimal** [lessthanoptimal/BoofCV#83]
Let people download and try the examples and demonstrations in BoofCV without compiling the library. Source code and all media dependencies will need to be included.

**Comment by brizey02** [comment]
I've been fighting to get the BoofCV Image Mosaic Applet working all day. I totally agree.

**Comment by lessthanoptimal** [comment]
Done. First iteration is now live on the website

https://boofcv.org/index.php?title=Applications#Examples_and_Demonstrations
