### ISSUE TITLE
How to convert a pinhole image to an equirectangular image

### ISSUE THREAD

**Issue by hpyfei** [lessthanoptimal/BoofCV#90]
Hello!

How to convert a pinhole image to an equirectangular image?

Can you bring me some advise?

Thank you!

**Comment by lessthanoptimal** [comment]
Hi could you post this question on the message board at:

[https://groups.google.com/forum/#!forum/boofcv](https://groups.google.com/forum/#!forum/boofcv)

This way there's a single place for people to search for "how do I" type questions. Github Issues is for bug reports and feature requests.

- Peter
