### ISSUE TITLE
Javadoc API lacks "Use" page

### ISSUE THREAD

**Issue by thhart** [lessthanoptimal/BoofCV#91]
Sometimes it is nice to have a usage page in the API doc to explore. With javadoc it will be generated with the "-use" option.

http://boofcv.org/javadoc/

**Comment by lessthanoptimal** [comment]
I've turned that option in Gradle/javadoc. Does look like it is useful

**Comment by thhart** [comment]
It is gone again. Current API does not have it.

**Comment by lessthanoptimal** [comment]
Should be fixed again. Reverted to Java 1.8 but fixed the issue. All though the new search doesn't seem to work.
