### ISSUE TITLE
Android 5.1 - API  (22) Support

### ISSUE THREAD

**Issue by ricardojlrufino** [lessthanoptimal/BoofCV#98]
Is it possible to decrease library compatibility to API 22?

**Comment by ricardojlrufino** [comment]
Solution
In the project gradle.properties, add:
android.enableD8=true

**Comment by lessthanoptimal** [comment]
coincidentally I worked on a major upgrade of the Android code this weekend. You can now use the Camera 2 API. The android example support API 21 and up.
