### ISSUE TITLE
ColorHsv value conversion not consistent

### ISSUE THREAD

**Issue by thhart** [lessthanoptimal/BoofCV#99]
The color conversion between RGB and HSV is not consistent for the value part. In ColorHsv.rgbToHsv the value output range is 0-255 (max image type value). However ColorHsv.hsvToRgb expects a value range 0-1. IMHO ColorHsv.rgbToHsv should normalize the value to a range 0-1 also.

**Comment by lessthanoptimal** [comment]
Could you provide an example? I'm not seeing this in the code. There are unit tests which use a range of 0 to 1 and 0 to 255

https://github.com/lessthanoptimal/BoofCV/blob/2a8ed06f88c206c9880bb8ae1b78a297d5cf3a4b/main/boofcv-ip/src/test/java/boofcv/alg/color/TestColorHsv.java

**Comment by thhart** [comment]
Will close, have to check the API better to understand the meaning of the different parameter spaces.
